### ISSUE TITLE
[keyboardShortcut.js] Some shortcuts have stopped working

### ISSUE THREAD

**Issue by rien333** [spicetify/cli#3034]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify version 1.2.37.701.ge66eb7bc, Copyright (c) 2024, Spotify Ltd
- Spicetify version: 2.36.11
```

### 📝 Description

I updated my spotify, which seems to have caused some shortcuts from the `keyboardExtension.js` extension to stop working.

The affected shortcuts include:

- Quit spotify (<kbd>Ctrl-Q</kbd>)
- Vim-style scrolling (h/j/k/l)

Notably, a few other shortcuts still work, such as <kbd>f</kbd> to start hinting and <kbd>/</kbd> to start searching.

**Comment by ohitstom** [comment]
what versions did you update to

**Comment by rien333** [comment]
I upgraded from what I think was `1.1.72.439` (or whatever version arch linux was on) to `1.2.37.701.ge66eb7bc`.

**Comment by ohitstom** [comment]
> I upgraded from what I think was `1.1.72.439` (or whatever version arch linux was on) to `1.2.37.701.ge66eb7bc`.

pls try the version in the pr

**Comment by rien333** [comment]
I will in a moment! Thanks for the quick fix.

**Comment by rien333** [comment]
Hm, everything involving scrolling remains broken on my end (using spotify's most recent linux release). That includes these shortcuts:

```javascript

// Scroll actions using 'j' and 'k' keys
j: { callback: () => createScrollCallback(SCROLL_STEP) },
k: { callback: () => createScrollCallback(-SCROLL_STEP) },

// Scroll to the top ('g') or bottom ('Shift+g') of the page
g: { callback: () => scrollToPosition(0) },
"shift+g": { callback: () => scrollToPosition(1) },
```

I'm using the most recent version of keyboardShortcut.js. 

Seems like `focusOnApp()` may be the culprit? That function gets called by all scrolling-related functions listed above. 


Perhaps noteworthy in that regard:

```javascript
function focusOnApp() {
	return document.querySelector(
		".Root__main-view .os-viewport, .Root__main-view .main-view-container__scroll-node, .Root__main-view .main-view-container__scroll-node > [data-overlayscrollbars-viewport]"
```

I'm not 100% sure what this does, but searching for `.os-viewport`  in the devtools gives me no results. `.Root__main-view .main-view-container__scroll-node` does exist, however.

**Comment by rien333** [comment]
@ohitstom ah, here is the issue I opened a while ago.  Could it be reopened?

**Comment by ohitstom** [comment]
> @ohitstom ah, here is the issue I opened a while ago.  Could it be reopened? 

sure can just repost your Spotify and spicetify versions 👍

**Comment by rien333** [comment]
Nvm, I turns out somebody updated keyboardShortcut.js in the mean time. The newer version works fine. So sorry for the noise.
