### ISSUE TITLE
Installing Spicetify gives error

### ISSUE THREAD

**Issue by TheDarkKnight69** [spicetify/cli#3037]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5
- Spicetify version: latest
```

### 📝 Description

while installing spicetify using the guide i get hit with an error:
![image](https://github.com/spicetify/cli/assets/91176991/d8d2e6fc-2b64-48f5-92a6-3b3b78c0ffac)

**Comment by TheDarkKnight69** [comment]
is there a way to manually install spicetify using the packages in the repo

**Comment by rxri** [comment]
Looks like old windows 10 or windows 7 installation. Either way, 1.2.5 is not supported and this is not an issue in cli.
