### ISSUE TITLE
wont let me install

### ISSUE THREAD

**Issue by thicthighslover** [spicetify/cli#3039]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

this happened while i was trynna install 

### 📸 Screenshots

![image_2024-05-22_004958312](https://github.com/spicetify/cli/assets/138119511/e5df1901-45a6-4ba4-b99b-c1f0e615a83d)

**Comment by rxri** [comment]
Related to marketplace, not cli. Should be already fixed tho
