### ISSUE TITLE
Sidebar marketplace icon misaligned

### ISSUE THREAD

**Issue by notmyung** [spicetify/cli#3042]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (32 bit) 1.2.38.720
- Spicetify version: spicetify v2.36.11
```

### 📝 Description

The extensions installed using spicetify are misaligned (e.g. marketplace)

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/160212673/ca45f86d-5c7f-475c-9bad-10df5d87bd1e)
![image](https://github.com/spicetify/cli/assets/160212673/bdf60c7d-6aba-430e-85cd-a23e717bfd35)

**Comment by rxri** [comment]
Fix is already merged into main branch

**Comment by notmyung** [comment]
How do you fix it?

**Comment by rxri** [comment]
By waiting for new spicetify release.

**Comment by notmyung** [comment]
Nvm bro i got it fixed
