### ISSUE TITLE
Left Sidebar items collapsing (non uniform sizes)

### ISSUE THREAD

**Issue by harsharora08** [spicetify/cli#3045]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Spicetify version: 2.36.11
```

### 📝 Description

The injected items on leftbar menu are not uniform with the already present items.

![image](https://github.com/spicetify/cli/assets/41362690/9d665cf7-3f42-4edf-99ff-252793a225f0)

The computed style in devtools are different too
![image](https://github.com/spicetify/cli/assets/41362690/a4ab9985-d65c-4622-a83a-546b1f825603)
![image](https://github.com/spicetify/cli/assets/41362690/e5eb9b45-ccc4-478a-a3ce-76de9f8381b6)

Also these elements get an underline when hovering which is not the normal case for sidebar menu items.
![image](https://github.com/spicetify/cli/assets/41362690/c9ddef47-44ea-4446-9a22-53261da09dbe)
So my guess is that these items are not inheriting properties from its parent. But I am not proficient in Web Development to solve this by mysell.

Let me know if this is just because of version difference. I know the current support goes till 1.2.37 so it can be this, I am not sure.

**Comment by rxri** [comment]
Already fixed by https://github.com/spicetify/cli/commit/11f85a23e16ffc843a7d99553d8b329158908b9a

**Comment by liangyi9812** [comment]
> So this will be auto-resolved when the next spicetify update comes, right?
> 
> Thanks for replying

我也发现了同样的问题
我将最新修改后的[spicetifyWrapper.js](https://github.com/spicetify/cli/blob/main/jsHelper/spicetifyWrapper.js)文件替换`~/.spicetify/jsHelper`文件夹的同名文件后解决了这个问题, 希望能帮助到你
