### ISSUE TITLE
Shuffle+ adding unknown song to queue

### ISSUE THREAD

**Issue by KoalaMistico** [spicetify/cli#3046]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Spicetify version: 2.36.11
```

### 📝 Description

What happens: When I use the "Play with Shuffle+" option on my main playlist (over 2000 songs) it adds music that I don't know (but sound related to my music taste) to the queue. This doesn't happen when using the same option on other (smaller) playlists.

What I expected: The option should create a queue only with the song included in the playlist.

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/82791845/c1c1df81-8c20-4d2f-ac15-180d5bffea02)

In this case, "Skills in Pills" isn't on my playlist, but I actually listen to other Lindemann songs.

**Comment by rxri** [comment]
Spotify's fault. Shuffle+ gets your playlist and uses data only from the response
