### ISSUE TITLE
event appchange does not fire anymore

### ISSUE THREAD

**Issue by arboriusphoto** [spicetify/cli#3047]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify für Windows (64 Bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.10
Theme: marketplace
Extensions: personal-scrobbles.js, genres.js, section-marker.js, listPlaylistsWithSong.js, spotifyGenres.js
Custom apps: marketplace
xpui_2024-05-17_1715913620018_a4a70a0
cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Runtime: Chrome
Build System: CMake
```

### 📝 Description

I have my own js file "personal-scrobbles.js" which fetches data from last.fm and shows for example the play count in the playlist list next to each song. 
It worked for over a year, when changing to a playlist that the event was fired. However, since December i guess it doesnt work anymore. 
I noticed in the issues that you removed the appchange event because apparently noone was using it (https://github.com/spicetify/cli/pull/2696). Is there another way to execute a script when a new page in spotify opens?

**Comment by rxri** [comment]
Spicetify.Platform.History

**Comment by arboriusphoto** [comment]
Thanks for the quick response! 

I managed to get it working:
  ```
let previousPathname = Spicetify.Platform.History.location.pathname;

  const checkHistoryChange = () => {
    const currentPathname = Spicetify.Platform.History.location.pathname;
    if (currentPathname !== previousPathname) {
        previousPathname = currentPathname;
        
        //do what I need to do when a history change is detected
    }
  };

// Check for history changes every 500 milliseconds
setInterval(checkHistoryChange, 500);
```

**Comment by rxri** [comment]
> Thanks for the quick response!
> 
> I managed to get it working:
> 
> ```
> let previousPathname = Spicetify.Platform.History.location.pathname;
> 
> const checkHistoryChange = () => {
>   const currentPathname = Spicetify.Platform.History.location.pathname;
>   if (currentPathname !== previousPathname) {
>       previousPathname = currentPathname;
>       
>       //do what I need to do when a history change is detected
>   }
> };
> 
> // Check for history changes every 500 milliseconds
> setInterval(checkHistoryChange, 500);
> ```

or just use `Spicetify.Platform.History.listen(({ pathname }) => { console.log(pathname) }))`. There's no need for `setInterval` here...

**Comment by arboriusphoto** [comment]
Thanks! That is what I was looking for.
