### ISSUE TITLE
Button/Icon alignment broken across spotify

### ISSUE THREAD

**Issue by p6thos** [spicetify/cli#3049]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70aOe
- Spicetify version: v2.36.11
```

### 📝 Description

As you can see in the screenshot I added, the button alignment is broken almost everywhere in spotify (this theme is a pretty mild example because it modifies a bunch of layout on its own). This has been the case for the last couple versions of spotify as far as I can remember. It does happen with all themes i tested. (Matte, Comfy, text, Default, One Punch)

### 📸 Screenshots

![copy of Screenshot 2024-05-28 013554](https://github.com/spicetify/cli/assets/77694883/f4bb531b-88bc-4b5a-9b87-24920ef3e7f0)

**Comment by rxri** [comment]
theme issue

**Comment by p6thos** [comment]
Is this a "theme developers have to update their themes" kind of Issue? Because i haven't found a single theme that doesn't look like this. Thanks for the quick answer btw :)
![Screenshot 2024-05-28 015720](https://github.com/spicetify/cli/assets/77694883/099262df-0b05-41b3-8303-33f35a2c3046)

**Comment by rxri** [comment]
Looked into it. Not an issue on theme(s) end. It's something on your end. I don't have these issues like you. Snippet or extension could cause that

**Comment by p6thos** [comment]
Oh ok, this is a fresh install, weird windows bug I assume. Thanks for your help!
