### ISSUE TITLE
Lyrics-plus not working or lyrics-plus taking infinite time to load lyrics on spotify

### ISSUE THREAD

**Issue by SuccessNEERAJ** [spicetify/cli#3050]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify 1.2. 38.720 for windows
- spicetify version 2.36.11
```

### 📝 Description

My spotify is not showing lyrics of songs even after i installed latest spicetify + lyrics-plus too. It goes for infinite loading of lyrics on fullscreen mode. Also there's no option showing for "lyrics-plus config" on my profile button of spotify. pls tell me how to fix this.

### 📸 Screenshots

![Screenshot 2024-05-28 205439](https://github.com/spicetify/cli/assets/113997753/057a33f4-3ce8-4b20-ac74-572a6d3d33d3)
![Screenshot 2024-05-28 215036](https://github.com/spicetify/cli/assets/113997753/a3866bcb-7f3b-4cf4-b206-0b2f5ab00621)

**Comment by rxri** [comment]
That's not lyrics plus. That's beautiful lyrics - not extension made by us

**Comment by SuccessNEERAJ** [comment]
> That's not lyrics plus. That's beautiful lyrics - extension which isn't made by us

Yea i know that's the extension, but the issue is lyrics are not showing up even if I don't install any extension. Lyrics-plus is installed. This issue is coming up when my Spotify automatically updated when i opened it yesterday night. Everything working fine but lyrics are not showing up🥲. Pls provide any help. I tried everything.
