### ISSUE TITLE
Fatal unlikat after updating Spotify

### ISSUE THREAD

**Issue by IronRUS** [spicetify/cli#3054]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.37.701.ge66eb7bc
- Spicetify version: v2.36.11
```

### 📝 Description

After Spotify update, Spicetify is not working due to failure to access `login.spa`

Error:
`fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/login.spa: permission denied`

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/38382271/3722e198-c258-4ae9-8d30-f2f06ebcfd76)

**Comment by rxri** [comment]
https://spicetify.app/docs/advanced-usage/installation#spotify-installed-from-flatpak
