### ISSUE TITLE
Every time I right click (playlists EPs, Albums, etc.) I get the message "Something went wrong try reloading the page"

### ISSUE THREAD

**Issue by At0m3543** [spicetify/cli#3059]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: latest
- I use MacOS
```

### 📝 Description

i cant right click on anything ever without it telling me to reload and then putting me back on the home page. 

### 📸 Screenshots

All I have installed:
<img width="532" alt="Screenshot 2024-06-05 at 2 17 05" src="https://github.com/spicetify/cli/assets/154020205/87d55db3-131b-40af-bd37-0e935c39458c">
(with a custom background)

**Comment by rxri** [comment]
Corrupted spotify installation. Not related to spicetify functionality and/or preprocess

**Comment by At0m3543** [comment]
> Corrupted spotify installation. Not related to spicetify functionality and/or preprocess

I uninstalled spicetify and it immediately stopped being an issue though?
