### ISSUE TITLE
Every time I right click on anything it tells me to reload (yes i am posting this again yes it is a spicetify issue i completely reinstalled spotify)

### ISSUE THREAD

**Issue by At0m3543** [spicetify/cli#3060]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: latest
- Using MacOS
```

### 📝 Description

Please don't immediately close the bug report this time if you'd be so kind.
Every time I right click on anything it tells me I need to reload. My spotify installation is the latest one, uncorrupted, spicetify is on the latest version. All I have installed are: Retroblur, Fix 'Liked' Icon, Auto-hide.
I also have a custom background added.

### 📸 Screenshots

<img width="477" alt="Screenshot 2024-06-05 at 2 28 58" src="https://github.com/spicetify/cli/assets/154020205/f87f33f7-5b3c-443f-bc4d-fb3a01c55953">

**Comment by rxri** [comment]
Please stop creating new issues. If you would have reinstalled spotify, you would have nothing installed in marketplace. Help is on our discord. Issues are for reporting an actual bugs, and this unfortunately or not is not the one.
