### ISSUE TITLE
Losing Extension within 1 day

### ISSUE THREAD

**Issue by Royalzzzzzz** [spicetify/cli#3068]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.39.578.g0ea3f38b
Spicetify v2.36.12
```

### 📝 Description

I have recently applied the script of spicefy yet I like the idea and extensions provided but I just observed that after 24 hour all the extensions which I add gets removed automatically and I have to add them again so is there any way to fix it or is that an issue from your side?

### 📸 Screenshots

n/a

**Comment by rxri** [comment]
Not related to spicetify. General help is available on our discord server

**Comment by theRealPadster** [comment]
Also chiming in here, since the spicetify marketplace (currently) stores all its settings in the spotify local storage API, it gets cleared by cache clearing tools. If you have something scheduled to clear caches or temp data, that might be doing it.
