### ISSUE TITLE
update

### ISSUE THREAD

**Issue by sentineldagoat** [spicetify/cli#3075]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify voor Windows (64-bits)
1.2.39.578.g0ea3f38b
- Spicetify version:2.36.12
```

### 📝 Description

how can i update spicetify?

### 📸 Screenshots

![specitfy](https://github.com/spicetify/cli/assets/173284441/6d8ecaa1-6202-4fe5-b084-b665d02551c0)

**Comment by rxri** [comment]
`spicetify update`. If it already says that it's up-to-date, run `spicetify restore backup apply`. On the other hand, issues are not for general help.
