### ISSUE TITLE
spicetify 

### ISSUE THREAD

**Issue by kittenvr** [spicetify/cli#3076]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.37.701.ge66eb7bc 
- Spicetify version:2.36.13
- bazzite os
```

### 📝 Description

if i follow the guide and it says prefs file not found so i follow https://spicetify.app/docs/advanced-usage/installation/#spotify-installed-from-flatpak and it gives error

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/103120356/c0f589b6-b5e1-49f7-8ced-2efa7f1ca386)

**Comment by rxri** [comment]
Spicetify does not resolve `~/` alias. Use absolute path
