### ISSUE TITLE
Something went wrong please try again

### ISSUE THREAD

**Issue by kalichT** [spicetify/cli#3077]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.10
- Spicetify version: 2.36.12
```

### 📝 Description

Hello I have a problem with launching spotify it says something says wrong try again and it wont load, when i uninstall spicetify it works, I tried reinstalling spotify and spicetify and nothing worked

### 📸 Screenshots

![obrázek_2024-06-20_230905220](https://github.com/spicetify/cli/assets/96803579/575df832-d09a-42e9-86c5-e9914aa37b3a)

(I have a different language)

**Comment by rxri** [comment]
Spicetify does not support Spotify version `1.2.10`. The oldest version supported is 1.2.13. You're also not on latest spicetify version
