### ISSUE TITLE
Issue in Installation on Mac

### ISSUE THREAD

**Issue by draviraja** [spicetify/cli#3081]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.40.599.g606b7f29
- Spicetify version: v2.36.13
```

### 📝 Description

While trying to install, getting the below errror and unbale to move forward as well.

### 📸 Screenshots

Last login: Sat Jun  1 15:00:25 on console
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
FETCHING Version 2.36.13
CREATING /Users/raviraja/.spicetify
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.13/spicetify-2.36.13-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
CREATING /Users/raviraja/.zshrc
APPENDING /Users/raviraja/.spicetify to PATH in /Users/raviraja/.zshrc

spicetify v2.36.13 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
n
spicetify Marketplace installation aborted
raviraja@eduroam-86-29 ~ % 
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh
FETCHING Version 1.0.2
MAKING FOLDER  /Users/raviraja/.config/spicetify/CustomApps
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % 
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh

FETCHING Version 2.36.13
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.13/spicetify-2.36.13-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/raviraja/.zshrc, continuing...

spicetify v2.36.13 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
y
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh

FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh
FETCHING Version 2.36.13
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.13/spicetify-2.36.13-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/raviraja/.zshrc, continuing...

spicetify v2.36.13 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
y
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % /Users/raviraja/Downloads
zsh: permission denied: /Users/raviraja/Downloads
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
FETCHING Version 2.36.13
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.13/spicetify-2.36.13-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/raviraja/.zshrc, continuing...

spicetify v2.36.13 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
y
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % spotify-path
zsh: command not found: spotify-path
raviraja@eduroam-86-29 ~ % spotify
zsh: command not found: spotify
raviraja@eduroam-86-29 ~ % 
~/.config/spotify/prefs
zsh: no such file or directory: /Users/raviraja/.config/spotify/prefs
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh -o /tmp/install.sh
sh /tmp/install.sh 1.2.1
FETCHING Version 1.2.1
DOWNLOADING https://github.com/spicetify/cli/releases/download/v1.2.1/spicetify-1.2.1-darwin-amd64.tar.gz
######################################################################### 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/raviraja/.zshrc, continuing...

spicetify v1.2.1 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
y
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh -o /tmp/install.sh
sh /tmp/install.sh 1.2.1
FETCHING Version 1.2.1
DOWNLOADING https://github.com/spicetify/cli/releases/download/v1.2.1/spicetify-1.2.1-darwin-amd64.tar.gz
######################################################################### 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/raviraja/.zshrc, continuing...

spicetify v1.2.1 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
n
spicetify Marketplace installation aborted
raviraja@eduroam-86-29 ~ % 
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
FETCHING Version 2.36.13
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.13/spicetify-2.36.13-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/raviraja/.zshrc, continuing...

spicetify v2.36.13 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
spicetify
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % y
zsh: command not found: y
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
FETCHING Version 2.36.13
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.13/spicetify-2.36.13-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/raviraja/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/raviraja/.spicetify/spicetify
REMOVING /Users/raviraja/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/raviraja/.zshrc, continuing...

spicetify v2.36.13 was installed successfully to /Users/raviraja/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
y
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
raviraja@eduroam-86-29 ~ %

**Comment by rxri** [comment]
Just restart your terminal session and run marketplace install script…
