### ISSUE TITLE
Lyrics Appearing and Disappearing in a split second when Fullscreen

### ISSUE THREAD

**Issue by Engoboy** [spicetify/cli#3093]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.41.434
- Spicetify version: 2.36.14
```

### 📝 Description

My Fullscreen lyrics just appear and disappear after a split second, I can't find it whatever I've been trying. Is there any t ype of fix?

### 📸 Screenshots

https://github.com/spicetify/cli/assets/64153757/f6dcb6dc-6d25-4c2f-ba41-8cd3ee02eb33

**Comment by rxri** [comment]
Not related to lyrics plus. It's something about queue panel in full screen.

**Comment by Engoboy** [comment]
> Not related to lyrics plus. It's something about queue panel in full screen.

what does queue panel mean?

**Comment by daksh2k** [comment]
@Engoboy check this https://github.com/daksh2k/Spicetify-stuff/issues/167#issuecomment-2199480598
