### ISSUE TITLE
glich

### ISSUE THREAD

**Issue by ssigmamale** [spicetify/cli#3095]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

works for one seconmd tham disapears

### 📸 Screenshots

https://github.com/spicetify/cli/assets/174838690/cba840a5-497c-4156-aed6-a2aa4998778c

https://github.com/spicetify/cli/assets/174838690/cdcceace-542f-49cc-800d-cff0350bd3eb

**Comment by rxri** [comment]
daksh2k's fullscreen extension is not made by us.
