### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by RedK22** [spicetify/cli#3096]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.36.13
- Spicetify version: 1.2.41.434
```

### 📝 Description

I tried to spicetify update using cmd, but it says Access Denied

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/92990671/d425126f-1c37-4b12-9a3a-116c3c7df7e3)

**Comment by rxri** [comment]
Defender blocked it.
