### ISSUE TITLE
Spicetify virus? 

### ISSUE THREAD

**Issue by Gitsstates** [spicetify/cli#3099]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
-
```

### 📝 Description

I encountered an error while updating Spicetify PUA:Win32/Packunwan

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/152910993/5ecd75a4-55d8-44bd-9564-f0aee8e8b1e3)

**Comment by venedikt-vad** [comment]
https://github.com/spicetify/cli/issues/3097

**Comment by rxri** [comment]
False positive. Happens from time to time
