### ISSUE TITLE
Forward and back keyboard shortcuts Feature return for Linux  

### ISSUE THREAD

**Issue by abirabedinkhan** [spicetify/cli#3104]
### 📝 Provide a description of the new feature

I would like to request the addition of forward and back keyboard shortcuts support for Linux users in Spicetify. Currently, this feature is available natively on Windows, but it is missing from the Linux version. Implementing this feature through an extension in Spicetify for Linux would greatly enhance the user experience by allowing for seamless navigation using keyboard shortcuts.

### ➕ Additional Information

Suggested Shortcuts:
- Forward: Ctrl + Right Arrow
- Back: Ctrl + Left Arrow
- Vol Up: Ctrl + Up Arrow
- Vol Down: Ctrl + Down Arrow

These shortcuts would align with common navigation shortcuts used in other applications, making it intuitive for users.

**Comment by rxri** [comment]
`keyboardShortcut` extension already implements shortcuts you're mentioning. https://github.com/spicetify/cli/blob/main/Extensions/keyboardShortcut.js

To use: `spicetify config extensions keyboardShortcut.js` and `spicetify apply`
