### ISSUE TITLE
Terminal Issue With Konsole

### ISSUE THREAD

**Issue by rickyrooroo229** [spicetify/cli#3105]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.37.701
- Spicetify version:1.0.2
- Bazzite Fedora 40
```

### 📝 Description

Konsole terminal does not create config but Ptyxis does, please fix or address

**Comment by rxri** [comment]
We do not support legacy version of Spicetify (v1)

**Comment by rickyrooroo229** [comment]
nvm I found the one that was trying to install v2.36.14, I only saw 1.0.2 when I first glance it, my bad

**Comment by rxri** [comment]
I don't understand the issue with the "creating config". Config is created when you first run any command in `spicetify`. Follow the instructions on our website, or install marketplace which will execute all commands for you

**Comment by rxri** [comment]
If you mean that it can't find `spotify_path` or `prefs_path`, follow the linux guide on our website: https://spicetify.app/docs/advanced-usage/installation#note-for-linux-users

**Comment by rickyrooroo229** [comment]
one terminal didn't make the config-xpui.ini file while the other did, Konsole and Ptyxis respectively

**Comment by rxri** [comment]
That's not related to spicetify though. Terminal has nothing to do with it also. We use syscalls provided with golang

**Comment by rickyrooroo229** [comment]
ok ty, still configuring Spicetify and I'm not too certain it's an issue that can be reemulated. I just wanted to make sure people knew in case they were using Konsole and run into this issue. If the problem isn't Spicetify or generally Terminal, then there isn't much else detail I can input other than this
