### ISSUE TITLE
fullAppDisplay ——Lyrics not working 

### ISSUE THREAD

**Issue by Phinsin666** [spicetify/cli#3108]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.41.434.g39a25e2c
- Spicetify version:spicetify v2.36.15
```

### 📝 Description

Hello,

When I press F11 to go full screen the lyrics don't load only an emoticon is displayed.

Clicking on the lyrics button will show the lyrics if it's not in full screen mode.

I do not know what to do.

Please help me.

### 📸 Screenshots

![1](https://github.com/user-attachments/assets/a5f28181-00ae-4992-a4aa-da252202835c)
![2](https://github.com/user-attachments/assets/c4014cd8-0fe0-4422-bd9d-0db4ce4ba181)

**Comment by rxri** [comment]
First screen shows Spotify lyrics. You need to refresh token inside Lyrics Plus config for Musixmatch to get it working

**Comment by Phinsin666** [comment]
@rxri Thank you !
