### ISSUE TITLE
Custom Controls

### ISSUE THREAD

**Issue by abhi-v-10** [spicetify/cli#3113]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: 2.36.15
```

### 📝 Description

Ive installed the custom control extension but when i click the controls like minimize maximize or close they dont wont and give the error attached below. What is wrong can someone help me in this please.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/86735e45-7e01-4276-98f0-93d0e14f639f)

**Comment by rxri** [comment]
That's not our extension.
