### ISSUE TITLE
Cannot see trashbin

### ISSUE THREAD

**Issue by Jyrabun** [spicetify/cli#3115]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.42.290.g242057a2
- Spicetify version: v2.36.15
```

### 📝 Description

I cannot see trashbin icons i have check around and saw an archived thread talking about this however it lead to no help since i do not posses a directory for %appdata%\Spotify\Apps\zlink  i have installed, reinstalled , cleared cache and directory to no avail

**Comment by rxri** [comment]
Enable it with the command (`spicetify config extensions trashbin.js` and `spicetify apply`) or install it via marketplace.

**Comment by Jyrabun** [comment]
> Enable it with the command (`spicetify config extensions trashbin.js` and `spicetify apply`) or install it via marketplace.

no such  luck tried both of these solutions

**Comment by Jyrabun** [comment]
im guessing this is being fixed then
