### ISSUE TITLE
Lyric-plus popup mode

### ISSUE THREAD

**Issue by BEST8OY** [spicetify/cli#3117]
### 📝 Provide a description of the new feature

An option to enable popup mode OR switching between tab mode and popup mode.

- What is the scenario this would be used?
Well, I personally like to see lyrics in front of me while doing other works but I can't as of now!

### ➕ Additional Information

There is a popup lyrics script but well that isn't connected to this lyric-plus custom app.

**Comment by rxri** [comment]
No, `popupLyrics` provides the same functionality (except conversions like hiragana etc)
