### ISSUE TITLE
`colorExtractor()` does not return PROMINENT anymore

### ISSUE THREAD

**Issue by muckelba** [spicetify/cli#3120]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify für Windows (64 Bit)
1.2.42.290.g242057a2
Spicetify v2.36.15
xpui_2024-07-12_1720793068427_242057a
cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Runtime: Chrome
Build System: CMake
```

### 📝 Description

`Spicetify.colorExtractor()` should return an object of found colors, but there's a discrepancy between the type defined here https://github.com/spicetify/cli/blob/ef624c5dddf5c5d975483854f036cb6e0b0e16a0/globals.d.ts#L542-L548
and the actual data coming from spotify:
![image](https://github.com/user-attachments/assets/d5b4bde5-d03d-4ae4-a7d4-054683cfcfd2)

The `PROMINENT` key is missing and the `DARK_VIBRANT` key is not present in the defined type. I *assume* that the object with the missing `preset` key contains the value for `PROMINENT`.

The object that `Spicetify.colorExtractor()` returns has an `undefined` key:
![image](https://github.com/user-attachments/assets/99e96f3a-b8e2-48f8-8984-c8cfd5324715)

I think the issues can be fixed by:
 * mapping the object with the missing `preset` key to `PROMINENT` 
 * adding `DARK_VIBRANT` to `globals.d.ts`

**Comment by rxri** [comment]
Spotify's fault. use `extractColorPreset` instead
