### ISSUE TITLE
Alt+Left Arrow shortcut doesn't work in the 'Keyboard Shortcut' extension.

### ISSUE THREAD

**Issue by sevennotfound** [spicetify/cli#3122]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.42.290.g242057a2 
- Spicetify version: v2.36.15
```

### 📝 Description

Pressing Alt + Left Arrow key is supposed to change the current song to the previous song (according to the code), but that doesn't work.

**Comment by rxri** [comment]
It's `ctrl + left arrow`.

**Comment by sevennotfound** [comment]
> It's `ctrl + left arrow`.

sorry it was a typo. ctrl + left arrow also doesn't work. I checked again

**Comment by rxri** [comment]
> > It's `ctrl + left arrow`.
> 
> sorry it was a typo. ctrl + left arrow also doesn't work. I checked again

Is your spotify window focused? because it needs to be. I also checked it, and works fine on my end

**Comment by sevennotfound** [comment]
> > > It's `ctrl + left arrow`.
> > 
> > 
> > sorry it was a typo. ctrl + left arrow also doesn't work. I checked again
> 
> Is your spotify window focused? because it needs to be. I also checked it, and works fine on my end

Yes it is focused and it still doesn't work. I'm on archlinux with gnome wayland if it helps.

**Comment by rxri** [comment]
> > > > It's `ctrl + left arrow`.
> > > 
> > > 
> > > sorry it was a typo. ctrl + left arrow also doesn't work. I checked again
> > 
> > 
> > Is your spotify window focused? because it needs to be. I also checked it, and works fine on my end
> 
> Yes it is focused and it still doesn't work. I'm on archlinux with gnome wayland if it helps.

Spotify doesn't fully support wayland. Use `xwayland` to launch spotify, and it should work, if not, then it's just because of no support from Spotify side
