### ISSUE TITLE
UPDATE basic docs / explain these commands

### ISSUE THREAD

**Issue by AlexDeFoc** [spicetify/cli#3126]
### 📝 Provide a description of the new feature

The basic documentation for "updating" the app without losing any configuration/extension/marketplace
I have been trying to create a automation script for me for updating the app but it's confusing cuz i stumbled upon these commands :
spicetify update -n

spicetify restore -n

spicetify backup apply -n
They are unclear in the documentation, and have experienced trying to move my configuration/saved config of spicetify extensions and all the customisation and after trying some commands in some order, it reset my config.
Please tell me what to do / fix / explain or update the documentation to be more clear, because in the basic usage i see only the update command / upgrade one for older version, but it what above the others? I think saving or doing a backup is needed cuz when updating there can be a reset. Thank you.

**Comment by rxri** [comment]
> and have experienced trying to move my configuration/saved config of spicetify extensions and all the customisation and after trying some commands in some order, it reset my config
No. Spicetify would never move it, neither reset your config.
`-n` is for no restart of Spotify so it doesn't matter.

If your data is missing, then don't clear spotify cache.
Either way, not related, not an issue.
