### ISSUE TITLE
Loopy Loop extension not working

### ISSUE THREAD

**Issue by senukalesan** [spicetify/cli#3128]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.40.599.g606b7f29
- Spicetify version: v2.37.0
```

### 📝 Description

After I add the loopy loop extension of spicetify to spotify from cmd cli, an error comes, error Custom app "loopyLoop.js" not found. https://spicetify.app/docs/advanced-usage/extensions#loopy-loop

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/b44b0613-c935-4b28-9c7e-1528c1e96228)

**Comment by rxri** [comment]
LoopyLoop is not a custom app but an extension. Configuration error
