### ISSUE TITLE
[Reddit] Clicking “More” dropdown doesn't show dropdown elements 

### ISSUE THREAD

**Issue by CheraHamza** [spicetify/cli#3136]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version : 1.2.44.405.g81fd6352
- Spicetify version : v2.37.1
- OS : Windows 11
```

### 📝 Description

When clicking the dropdown “More” in the Reddit app, the full dropdown never shows and only shows a line as shown in the image below.

### 📸 Screenshots

![ScreenRecording2024-08-14115855-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/18cf6344-8f69-4178-8060-a316b6cbabb2)

**Comment by rxri** [comment]
Im 99% that just means there's nothing more to show but `More` button has broken visibility in code

**Comment by CheraHamza** [comment]
Hey @rxri. I know there are more to show because when I increase the window's width, the hidden elements become visible.
![ScreenRecording2024-08-15140939-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/d70e3478-8eb9-40ad-8621-8066b5a80e36)

**Comment by rxri** [comment]
Idk can be opened, but I really am not going to bother fixing it, so if someone wants to; feel free.
