### ISSUE TITLE
Spicetify Documentation: Is there an error with the playUri method and PlayerAPI?

### ISSUE THREAD

**Issue by yanyou5** [spicetify/cli#3138]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify macOS (Intel) 版
1.2.44.405.g81fd6352
Spicetify v2.37.1
Theme: marketplace
Custom apps: marketplace, library
xpui_2024-08-09_1723192885229_81fd635
cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Runtime: Chrome
Build System: Bazel
```

### 📝 Description

How can I play a specific song from a playlist based on the track index within the playlist? 
I’ve tested 5 methods, but none of them work. 

I created a playlist and need to implement the functionality to play a song by clicking on it, 
based on the track index within the playlist. I also need to implement previous and next track functionality.

Here is the debug information to ensure that the playlistUri is correct and the index value is correct:
```
VM3648:2594 Current playing URI: spotify:track:1VdQEI6hCcBlioAxE0xaYj
VM3648:2594 Playlist URI: spotify:playlist:1ZFSnczcrvGBB7dNU2PCPg
VM3648:2594 Index: 3
```
### **1. Using the playUri method:**
`await Spicetify.Player.playUri(playlistUri, { context: { uri: playlistUri }, options: { index } });`
### **2. Using the playUri method:**
`await Spicetify.Player.playUri(playlistUri, {}, { index: index });`
### **3. Using Spicetify.Platform.PlayerAPI.play:**
```
await Spicetify.Platform.PlayerAPI.play({
    uri: playlistUri,
    contextTrack: {
        uri: thisTrackUri,
        uid: track.id,
        metadata: {
            is_playable: true
        }
    },
    contextIndex: index,
    options: {
        skipTo: {
            track_index: index
        }
    }
});
```
_Error: TypeError: Cannot read properties of undefined (reading 'featureIdentifier')_
### **4. Using Spicetify.Platform.PlayerAPI.play:**
```
await Spicetify.Platform.PlayerAPI.play({
    contextUri: playlistUri,
    trackUri: thisTrackUri,
    options: {
        skipTo: {
            index: index
        }
    }
});
```
_Error: TypeError: Cannot read properties of undefined (reading 'featureIdentifier')_
### **5. Using the CosmosAsync method:**
```
await Spicetify.CosmosAsync.post("sp://player/v2/main", {
    context_uri: playlistUri,
    offset: { position: index },
    position_ms: 0
});
```
_Error: Error: POST request to sp://player/v2/main request failed with error code -1 (Resolver not found!)_

I have modified the code many times, tested it many times, and consulted AI, but I am not sure if there is an issue with the documentation.
**Can you help me figure out how to play a specific song from a playlist based on the track index within the playlist?**

**Comment by rxri** [comment]
You already asked on discord. This is not a bug in spicetify. Just wait for the response on discord

**Comment by rxri** [comment]
You can’t play song with the index from the playlist btw
