### ISSUE TITLE
Spotify not Loading anything after installing Spicetify

### ISSUE THREAD

**Issue by gitultra75848** [spicetify/cli#3139]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.44.405.g81fd6352
- Spicetify version: 2.37.1

- OS: MacOS 14.5
- Computer: MacBook Pro M1 Pro Late 2021
- Memory: 16GB
```

### 📝 Description

I installed Spicetify using the curl installer, applied everything then opened the Client, and almost nothing loaded except just the home page with recent playlists and recommended songs. Clicking the Profile gives an error and clicking a playlist puts you in an infinite loading cycle.

### 📸 Screenshots

<img width="1372" alt="Screenshot 2024-08-18 at 10 49 08 AM" src="https://github.com/user-attachments/assets/f6411b47-717d-440c-97c2-d15fc572ccdb">
<img width="1373" alt="Screenshot 2024-08-18 at 10 49 14 AM" src="https://github.com/user-attachments/assets/851e58ee-2eef-4633-91bc-0d0ac90e7afd">
<img width="1378" alt="Screenshot 2024-08-18 at 10 49 25 AM" src="https://github.com/user-attachments/assets/191bc96a-e19d-4481-a433-7cce0d1a0ed7">

**Comment by rxri** [comment]
1. That's not 1.2.44 
2. That's not related to spicetify

**Comment by gitultra75848** [comment]
> 1. That's not 1.2.44
> 2. That's not related to spicetify

...Yes, It is 1.2.44. 
I don't understand how it wouldn't be related to Spicetify as I said previously, It only happend After I installed Spicetify.

**Comment by rxri** [comment]
Again, that's not 1.2.44. I already see it via the UI you have. Reinstall Spotify with using [AppCleaner](https://freemacsoft.net/appcleaner/)

**Comment by gitultra75848** [comment]
> Again, that's not 1.2.44. I see it via the UI you have. Reinstall Spotify with using [AppCleaner](https://freemacsoft.net/appcleaner/)

Thanks, that fixed it.
