### ISSUE TITLE
Spicetify on fresh install not working

### ISSUE THREAD

**Issue by Ssionn** [spicetify/cli#3140]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.44.405.g81fd6352
- Spicetify version: 2.37.1
```

### 📝 Description

I've just installed spotify through the site and installed spicetify using the spicetify website, but it's not working for some reason. No error messages are popping up.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/5a2b5b2d-dd6d-4334-b44b-5c5d22b18f89)

**Comment by rxri** [comment]
Help is on our discord server, not in issues since it's not a bug.
