### ISSUE TITLE
Spicetify on linux mint error cant find location

### ISSUE THREAD

**Issue by gumbax3455** [spicetify/cli#3141]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.42.290.g242057a2
- Spicetify version: none
```

### 📝 Description

I installed spotify using snap on my linux mint cinnanom 22 comuter. Now i want to install spicetify, so i ran the commant : curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
as descriped on https://spicetify.app/docs/getting-started/
but it gives me this error: error /usr/share/spotify/ is not a valid path. Please manually set "spotify_path" in config-xpui.ini to correct directory of Spotify.
I checked and there is a similar post but i cant find the solution that the guy had found. I dont know the path of my spotify install. 
I am new to linux

**Comment by gumbax3455** [comment]
did a little bit debugging whit chat-gpt. He suggested changing the path, which i did. Now, spicetify returns with no errors, but does nothing to my spotify.
here the chat-gpt chat to understant what i did: https://chatgpt.com/share/000744d6-3f41-41e1-866c-2f1ff934280d

**Comment by rxri** [comment]
We do not support snap. It says so in docs. Use spotify from the APT repo.
