### ISSUE TITLE
fatal zip: not a valid zip file

### ISSUE THREAD

**Issue by TechySkills** [spicetify/cli#3142]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: Current version: 2.37.1, but trying to download Latest release: 2.37.2
```

### 📝 Description

C:\Users\alisu>spicetify update
spicetify v2.37.1
Fetch latest release info:
OK
info Current version: 2.37.1
info Latest release: 2.37.2
Downloading:
OK
Extracting:
info If fatal error is "Permission denied", please check read/write permission of spicetify executable directory.
info However, if you used a package manager to install spicetify, please upgrade by using the same package manager.
fatal zip: not a valid zip file

C:\Users\alisu>spicetify update
spicetify v2.37.1
Fetch latest release info:
OK
info Current version: 2.37.1
info Latest release: 2.37.2
Downloading:
OK
Extracting:
info If fatal error is "Permission denied", please check read/write permission of spicetify executable directory.
info However, if you used a package manager to install spicetify, please upgrade by using the same package manager.
fatal zip: not a valid zip file

Spicetify doesnt want to get updated rather says it is not a valid zip file. Please fix this issue.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/38d45a57-b2b7-4506-b4f5-eaa78845cdf2)

**Comment by rxri** [comment]
because it didn't even build them yet...
