### ISSUE TITLE
Spicetify is gone MacOS

### ISSUE THREAD

**Issue by BitGrub** [spicetify/cli#3145]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.2.33.1039.g8ddb5918
- Spicetify version: 2.37.4
```

### 📝 Description

After updating to spicetify 2.37.4 from 2.37.1 using "spicetify update", Spotify is unspicetified. Tried rerunning the install scripts with and without marketplace and it still doesn't come back. I Updated without issue on Windows 11. Help?

**Comment by rxri** [comment]
What `Spotify is unspicetified` means? Spicetify works just fine on every platform. If you need help with configuring spicetify, please do so on our discord server.

**Comment by BitGrub** [comment]
> What `Spotify is unspicetified` means? Spicetify works just fine on every platform. If you need help with configuring spicetify, please do so on our discord server.

It means it's like stock Spotify. unspicetify, without spicetify. Spotify minus spicetify. Idk how else to explain it.

**Comment by rxri** [comment]
`spicetify backup apply`...
