### ISSUE TITLE
Marketplace and extensions not functioning on v2.37.4

### ISSUE THREAD

**Issue by VireV** [spicetify/cli#3148]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.32.985 (previously tested with 1.2.36 as well)
- Spicetify version: 2.37.4
```

### 📝 Description

The marketplace or any extensions do not function on Spicetify v2.37.4. **However, going back to v2.37.2 fixed this issue.** I tested this on Spotify 1.2.36 and then 1.2.32 (I tried changing the Spotify version first but to no avail).

Extensions such as New releases or lyrics-plus were not working. Even functionalities such as the experimental features and sidebar config buttons were missing from the profile picture dropdown. 

I am confident that the Spicetify was applied as it was included in the "About Spotify" popup, however no extensions or apps (marketplace) were being run. 

Thank you :)

**Comment by VireV** [comment]
The problem continues after updating to v2.37.5. No extensions, marketplace (custom apps), or even the experimental & sidebar config options. Also like before is that Spicetify is included in the About Spotify popup.

On v3.37.2, the console shows "Initializing Spicetify Marketplace v1.0.2" and "Loaded Marketplace extension" while on v3.37.5 it shows messages about the Spicetify Wrapper?
![Screenshot 2024-08-27 183633](https://github.com/user-attachments/assets/ea43134c-47c1-4dc8-a27f-2a9379f6da11)

No dice, but thanks again.

**Comment by rxri** [comment]
ah nvm i see what happened wtf

**Comment by rxri** [comment]
Fixed with v2.37.6

**Comment by VireV** [comment]
Sorry again but nope :P

Is my config unusual? (I removed my names from it and changed the file extension to .txt so I could upload)
[config-xpui - Name removed.txt](https://github.com/user-attachments/files/16767122/config-xpui.-.Name.removed.txt)

**Comment by rxri** [comment]
on 1.2.36 it works, on 1.2.32 there's another edge case for it.

**Comment by VireV** [comment]
It's applied, but not working as you would expect.
![image](https://github.com/user-attachments/assets/22c21448-8556-4b9d-aaa1-8d7a74bf7b7e)

**Comment by rxri** [comment]
[spicetifyWrapper.zip](https://github.com/user-attachments/files/16767617/spicetifyWrapper.zip)
Put this file into `%localappdata%\spicetify\jsHelper` and run `spicetify apply` and lmk if it works for you

**Comment by VireV** [comment]
Ayyyy, this fixed it. Extensions, apps, sidebar config dropdown option and such all work as expected.
