### ISSUE TITLE
New Releases Section Stuck on Endless Loading

### ISSUE THREAD

**Issue by toxtodo** [spicetify/cli#3149]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: spicetify v2.37.7
- Spicetify version: Spotify for Windows (64 bit)
  1.2.44.405.g81fd6352
```

### 📝 Description

After I updated spicetify, the New Releases section just hangs there, stuck on an endless loading screen. I tried restarting Spotify, even uninstalled and reinstalled the whole thing, but nada, no change at all.

I saw some old responses where you mentioned there wouldn't be any more support for this app, but it looks like you've kinda decided to keep updating it, 'cause the last tweak was like 3 weeks ago

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/b1fddf65-9923-4fb1-9aed-3f07f2396661)
![image](https://github.com/user-attachments/assets/8eaaf523-60e1-4916-bbc6-4e2bb0b2e41d)

**Comment by rxri** [comment]
Spotify related. They removed the endpoint.

**Comment by toxtodo** [comment]
> Spotify related. They removed the endpoint.

so there's no way to fix this, huh? That's a bummer, 'cause honestly, this app is the best one I've come across. ;(

**Comment by rxri** [comment]
I mean it probably is but no one looked into it yet

**Comment by Satanarious** [comment]
Spotify fix this

**Comment by guiltlab** [comment]
I miss this so much :(
Is it possible to get it back by downgrading Spotify or is it completely dead at the moment ?

**Comment by immaterials** [comment]
> I miss this so much :( Is it possible to get it back by downgrading Spotify or is it completely dead at the moment ?

It is possible. I had to downgrade to 1.2.43.420 (the version before the most recent UI change) to get it working again.
