### ISSUE TITLE
Intermittent issue: Lyrics-plus sidebar button still sometimes present even with the option to remove it is enabled.

### ISSUE THREAD

**Issue by VireV** [spicetify/cli#3151]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.32.985
- Spicetify version: v2.37.7
```

### 📝 Description

When opening Spotify (or refreshing in dev-tools), about 10% of the time, the Lyrics-plus sidebar button does not get removed. This should have happened as the "Replace Spotify's lyrics button" option is enabled. 

I went back and tested on v2.37.2 and it removed the button in that version every time (even if it sometimes took a second), so this seems to be new.

Thanks :)

### 📸 Screenshots

This screenshot shows both the sidebar button and the replaced native lyrics button being shown at once, with the option enabled.

![Screenshot 2024-08-30 004820](https://github.com/user-attachments/assets/f210929b-4c44-4cb5-9e89-61b40b5bdf86)

**Comment by rxri** [comment]
Nothing we can do.

**Comment by VireV** [comment]
Can't you delay the removal of the sidebar button until after it's loaded? It's strange that you can insert something but not take it away
