### ISSUE TITLE
[FEATURE REQUEST] Allow to add our own GitHub token for requests

### ISSUE THREAD

**Issue by EDM115** [spicetify/cli#3154]
### 📝 Provide a description of the new feature

We could have a new setting called `github_token` which would take a [Github PAT](https://github.com/settings/tokens). Even if this token have no rights, it would allow to authenticate on GitHub's API on the behalf of an user.  
As explained [here](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28) :  
> The primary rate limit for unauthenticated requests is 60 requests per hour.  

So a new user that just browses the Marketplace, installs apps and applys will hit the limit very easily :  
```pwsh
   ❯❯ C:\Windows\System32
    ❯ spicetify apply
spicetify v2.37.7
error Cannot fetch latest release info
error GitHub response: API rate limit exceeded for re.da.ct.ed. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
...
```

Being authenticated gives us much more freedom :  
> You can use a personal access token to make API requests.
> ...
> All of these requests count towards your personal rate limit of 5,000 requests per hour.  

### ➕ Additional Information

This would fix reliably #2998 and #1981 (getting 403 errors and "Error parsing Markdown" in-app)  
If the setting isn't set or the token is invalid, it would do an unauthenticated call just like it currently does. Else, it would do all GitHub requests authenticated.  
Docs would probably need an update for this, maybe in the FAQ.  
  
More overall info [here](https://docs.github.com/en/rest/rate-limit/rate-limit?apiVersion=2022-11-28)

**Comment by rxri** [comment]
No. We won't. This ratelimit is enough unless you reload Spotify every 5 seconds. `spicetify update` throwing ratelimit? Just wait 15 minutes. 403 error means that there's no README.

**Comment by EDM115** [comment]
> 403 error means that there's no README  
  
wrong (tried with 2 random extensions) :  

https://github.com/user-attachments/assets/1dc4b507-5085-4a8b-8684-842868025d10

**Comment by FrzMtrsprt** [comment]
This can also happen if you share the same ip address with someone who abuses the github api, or if you're in a really big subnet, which is quite common for those who can't access spotify without a vpn or those on campus.

**Comment by rxri** [comment]
Still am not sure how it's related to the cli itself. It would only apply to the update command which you don't really use frequently so this rate limit thingy wont affect you

**Comment by EDM115** [comment]
> Still am not sure how it's related to the cli itself.
  
indeed it isn't but where tf is the repo with spicetify's actual source code ?  
Out of the publicly available repos, I guess only 3 would be related to what's actually installed by the cli :
- https://github.com/spicetify/classmaps : probably for css, no readme whatsoever
- https://github.com/spicetify/modules : allegedly for v3, so probably doesn't concern our problem
- https://github.com/spicetify/hooks : the only one left, with no more info on the readme, no docs and commit names doesn't help at all

I'd be glad to open the issue in the appropriate repo and even make a PR for this, but god damn it's nowhere to be found.  

> It would only apply to the update command which you don't really use frequently
  
Last time I checked, `spicetify backup`, `spicetify apply` and others all triggers an update (or at least a check of it, which counts towards the hourly unauthenticated gh requests) :  
```pwsh
   ❯❯ C:\Windows\System32
    ❯ spicetify backup
spicetify v2.38.3
info Spicetify up-to-date
info There is available backup.
info Clear current backup:
warning After clearing backup, Spotify cannot be backed up again.
info Please restore first then backup, run "spicetify restore backup" or re-install Spotify then run "spicetify backup".
                                                                                                                           ❯❯ C:\Windows\System32
    ❯ spicetify apply
spicetify v2.38.3
info Spicetify up-to-date
Overwriting themed assets:
OK
success Custom CSS is updated
success Theme's JS is updated
Applying additional modifications:
OK
Transferring custom apps:
OK
success Spotify is spiced up!
success Enabled DevTools!
```

also I read your announcement on discord so I definitely understand that this small problem is absolutely not a priority at all

**Comment by rxri** [comment]
Normal user won't run `backup`, `apply` or `update` 60 times in the hour, because it's literally not needed to do so. What you're looking for is https://github.com/spicetify/marketplace. It's pinned on the organization so I don't know how you couldn't find it. You listed 3 of v3 repos so yeah idk but marketplace is what you're looking for

**Comment by EDM115** [comment]
my bad, I thought that the marketplace repo was only holding responsibility for listing some extensions and themes and wasn't what actually implements spicetify's core functionnalities

**Comment by rxri** [comment]
I'm sorry? Marketplace doesn't hold any of cli core functionalities. If you want to fix 403, and rate limit errors in marketplace do it in marketplace's repo.

**Comment by WybeBosch** [comment]
I must be blind
The error message says read the docs, but i cant find it in the docs?
```
spicetify v2.37.7
Fetch latest release info:
error Cannot fetch latest release info
error GitHub response: API rate limit exceeded for 185.90.186.154. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

Where can i find in the docs more info about how to fix this? 

https://spicetify.app/docs/advanced-usage/command-line-interface
Contains no info about update going wrong

https://spicetify.app/docs/faq/#after-spotifys-update-running-spicetify-apply-or-spicetify-update-breaks-spotify
Is just about update breaking and having to apply backup

https://spicetify.app/docs/development/spotify-cli-flags
Looks handy, doesnt help me solve being rate limited by github.

Those are all the docs i can find related to cli or update

======================================

Reading this current thread the solution is: Wait?
im not spamming the github api or anything : s

Is spicetify update all what it does git clone the new release somewhere? 
is this something i could do by hand perhaps? (So i dont get against the rate limit?)

**Comment by EDM115** [comment]
indeed it's github telling you to read *their* docs  
and after all, spicetify is probably not the only app on my system (especially as a dev) which makes unauthenticated requests to github so that 60/h cap can be easily surpassed

**Comment by WybeBosch** [comment]
Is there another way to update Spicetify except for running spicetify update via the cli?

**Comment by Kovinda** [comment]
Any luck with this guys ?

**Comment by EDM115** [comment]
@WybeBosch that's exactly the point I tried to make but they won't listen...  
the only way i'm thinking of is to have a program that listen and intercepts all network requests and add headers with your PAT for every request to the GitHub API, but honestly *who* would do it ? 😂  
  
about the requests on every command, in your `spicetify/config-xpui.ini` set this to disable it (you would need to run `spicetify update` manually but at least not **every** command would run it) :  
```ini
[Setting]
check_spicetify_update = 0
```

**Comment by EDM115** [comment]
> While i agree that nobody would run `spicetify backup apply` 60 times an hour  
  
Nobody does, but browsing the Marketplace does when you click on an extension to display its description.  
And considering the number of extensions nowadays, a new user can hit this limit really fast if they check every extension to know what they actually do (see the video at https://github.com/spicetify/cli/issues/3154#issuecomment-2323339769).

**Comment by rxri** [comment]
> that's exactly the point I tried to make but they won't listen...

I'm listening. I responded to your request and I disagreed with it. I, not others, me. Regardless if we would want to implement it or not, there's no place to put this token because `config-xpui.ini` SHOULD NOT hold stuff like Authorization tokens, and also, how would cli share this token with the wrapper? Patch it into the javascript files? Yeah, that doesn't sound good at all. Like I said, I'm not changing my mind and we're not going to consider it.
As always, feel free to fork it and add it manually as you wish.

**Comment by EDM115** [comment]
> `config-xpui.ini` SHOULD NOT hold stuff like Authorization tokens. Many of our users share their dotfiles  
  
very true, i share these files too.  
  
> On the other hand, how would cli share this token with the wrapper? Patch it into the javascript files?  
  
or use an env var called `spicetify_gh_pat` or whatever, i mean not everything needs to be in files (this poses other issues tbh, and using a credentials manager for this task would be highly overkill ngl)  
  
> Checking extension's README does not count towards the API ratelimit  
  
thx for the info ! but i still wonder why it wasn't able to fetch the content and dropped 429's, i don't think i was hitting the [5k limit](https://stackoverflow.com/a/74960542) either... mystery will never be solved

**Comment by WybeBosch** [comment]
Sorry if this conversation got a bit heated, this was never my intention, im very happy that people put so much effort and passion in a free tool. 

I understand why you do not want the headache of adding support for a PersonalAccesToken. 
Feel free to shootdown this PR, but i thought maybe if i put in the work and tested a solution. 

It could provide something to read back on for the future, or atleast show that im invested in this topic
i created a PR that adds support for a GITHUB_TOKEN 
https://github.com/spicetify/cli/pull/3271

thats read from the env from wherever the spicetify update command is ran

**Comment by rxri** [comment]
> thx for the info ! but i still wonder why it wasn't able to fetch the content and dropped 429's, i don't think i was hitting the [5k limit](https://stackoverflow.com/a/74960542) either... mystery will never be solved

because you're hitting the 429 on the endpoint to manifest. I think it's some stupid thing that fetches manifest when you want to click the readme am sure.

**Comment by de-served** [comment]
Or when a user adds an extension, reloads to test it (what it does or broken), remove+add next+reload.
Now spotify autoupdated, I entered `spicetify backup apply` and got this error again (and now I have "dead" spotify until zeroing rates or reinstall spotify/restore from backup but without spicetify, Psiphon VPN didn't help - spicetify didn't forward traffic through this tunnel)
So feature is must be.

**Comment by adventuretc** [comment]
I got this out of the blue yesterday and also today. I can't imagine how I hit the limits, I did nothing with Github other than this installation.

My idea is that the CLI could print the URL of the file it tried to download and you can download by hand in your browser, and then, if the file is found in the cwd, Spicetify resorts to using that one. Is this realistic?

Edit: I waited >15 minutes and luckily Github gave way.

                   

> APPLYING
> spicetify v2.42.3
>  error  Cannot fetch latest release info
>  error  GitHub response: API rate limit exceeded for <ip>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
> 
> Preprocessing
>  warning  Failed to fetch remote CSS map      
> GitHub response: API rate limit exceeded for <>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
>
