### ISSUE TITLE
Minimize/Maximize Button overlaps Profile icon

### ISSUE THREAD

**Issue by Dan33185** [spicetify/cli#3155]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.45.454.gc16ec9f6
Spicetify v2.37.7
Theme: Matte / matte
Extensions: hidePodcasts.js, fullAlbumDate.js, spotifyBackup.js, adblock.js, extended-copy.js
Custom apps: marketplace
```

### 📝 Description

The minimize/maximize buttons overlap the profile icon below it, this is not theme dependent as it does it on almost every theme I have tried.

### 📸 Screenshots

![Untitled](https://github.com/user-attachments/assets/5a8126e3-59a1-4768-b480-2a597476d3fb)

**Comment by rxri** [comment]
Then enable global navbar. That's spotify thing, not spicetify's.

**Comment by Dan33185** [comment]
> Then enable global navbar. That's spotify thing, not spicetify's.

That doesn't fix it...guess I'll live with it as this report was shut down fast.

**Comment by rxri** [comment]
> as this report was shut down fast.

Again, this is not related to spicetify. Height of these buttons was adapted to Global navbar and we will not do anything about it.
