### ISSUE TITLE
Spotify 1.2.46 causes spicetify to panic

### ISSUE THREAD

**Issue by craiggeil** [spicetify/cli#3158]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.46.462
- Spicetify version: 2.37.7
```

### 📝 Description

Try to install latest on Windows 11 machine
Get the following error:
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: main
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/cli/src/preprocess.exposeAPIs_main({0xc000588000, 0x1b617d})
        /home/runner/work/cli/cli/src/preprocess/preprocess.go:564 +0x573
github.com/spicetify/cli/src/preprocess.Start.func1.1({0xc000c02000, 0x1b5b34})
        /home/runner/work/cli/cli/src/preprocess/preprocess.go:103 +0x193
github.com/spicetify/cli/src/utils.ModifyFile({0xc001c08000, 0x43}, 0xc0000979e0)
        /home/runner/work/cli/cli/src/utils/utils.go:221 +0xb2
github.com/spicetify/cli/src/preprocess.Start.func1({0xc001c08000, 0x43}, {0xb45a08?, 0xc000134070?}, {0xc000097c80?, 0xa26c13?})
        /home/runner/work/cli/cli/src/preprocess/preprocess.go:91 +0x152
path/filepath.walk({0xc001c08000, 0x43}, {0xb45a08, 0xc000134070}, 0xc000097c80)
        /opt/hostedtoolcache/go/1.21.13/x64/src/path/filepath/path.go:477 +0xff
path/filepath.walk({0xc0000134c0, 0x3b}, {0xb45a08, 0xc001d5e000}, 0xc00009bc80)
        /opt/hostedtoolcache/go/1.21.13/x64/src/path/filepath/path.go:501 +0x257
path/filepath.Walk({0xc0000134c0, 0x3b}, 0xc00169fc80)
        /opt/hostedtoolcache/go/1.21.13/x64/src/path/filepath/path.go:572 +0x66
github.com/spicetify/cli/src/preprocess.Start({0xb41608, 0x6}, {0xc000012300?, 0x36?}, {0x0?, 0x0?, 0x0?, 0x0?})
        /home/runner/work/cli/cli/src/preprocess/preprocess.go:85 +0x2b1
github.com/spicetify/cli/src/cmd.Backup({0xb41608, 0x6})
        /home/runner/work/cli/cli/src/cmd/backup.go:68 +0x3dc
main.main()
        /home/runner/work/cli/cli/spicetify.go:274 +0xb85
spicetify v2.37.7

**Comment by amd64fox** [comment]
show full version spotify 

something like this:
1.2.46.462.gxxxxxxxx

**Comment by craiggeil** [comment]
gf57913e0

**Comment by amd64fox** [comment]
ty

links for those who want to reproduce this problem:

WIN32:
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.46.462.gf57913e0-290.exe

WIN64:
https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.46.462.gf57913e0-290.exe

WIN-ARM64:
https://upgrade.scdn.co/upgrade/client/win32-arm64/spotify_installer-1.2.46.462.gf57913e0-290.exe

OSX:
https://upgrade.scdn.co/upgrade/client/osx-x86_64/spotify-autoupdate-1.2.46.462.gf57913e0-267.tbz

OSX-ARM64:
https://upgrade.scdn.co/upgrade/client/osx-arm64/spotify-autoupdate-1.2.46.462.gf57913e0-267.tbz

**Comment by rxri** [comment]
Again, per spicetify release notes, we don't support 1.2.46, as this is fairly new version, don't expect us to fix it very fast

**Comment by IgorIsaiasBanlian** [comment]
I want to confirm that I have the same issue here, with the same version of Spotify, the same version of Spicetify, and I am also using Windows 11.

**Comment by rxri** [comment]
This panic has been resolved with https://github.com/spicetify/cli/commit/aa4ac602360f06836ac69e7bc995a9f9ae33159d. However navlinks have not been fixed yet
