### ISSUE TITLE
big icon

### ISSUE THREAD

**Issue by Pave1c** [spicetify/cli#3159]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: lasters
- Spicetify version: lasters
```

### 📝 Description

quite an annoying bug, hopefully it can be fixed in the next update

### 📸 Screenshots

![Annotation 2024-09-07 024540](https://github.com/user-attachments/assets/3467b8c1-704b-4100-b839-95ff557b1253)

**Comment by rxri** [comment]
Don't know what latest is. That's not related to spicetify (core itself) but the actual extension probs
