### ISSUE TITLE
Exposed components not always resolving

### ISSUE THREAD

**Issue by ohitstom** [spicetify/cli#3160]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.45.454.gc16ec9f6
Spicetify v2.37.7
xpui_2024-08-26_1724674643080_c16ec9f
cef_127.3.4+ge9e2e14+chromium-127.0.6533.100
Runtime: Chrome
Build System: Bazel
```

### 📝 Description

some components are not always resolving, to be clear this isnt a matter of trying to use them before they are resolved - its more that they are NEVER resolving (but only on some startups).

in my case the Toggle react component is 1/3 boots not ever being resolved in the wrapper leaving me with these errors on any extension that uses this component:

![image](https://github.com/user-attachments/assets/b2cbd941-d8d2-4ca8-b3ad-8bc3518c6bf4)

To test this issue yourself:
- Open Spotify
- inspect element
- run `Spicetify.test()`
- refresh and run `Spicetify.test()` and see that every couple refreshes there are different missing components or functions

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/1a67eca7-d1b4-4bef-aaf9-c8944cb1be0a)
![image](https://github.com/user-attachments/assets/573ca884-53f4-4694-8dc3-0d33319e9d01)
![image](https://github.com/user-attachments/assets/6bfb721b-b281-4f46-954f-81cefb3b28e1)

**Comment by rxri** [comment]
Reinstall your Spotify

**Comment by ohitstom** [comment]
this is still happening regardless of reinstall
