### ISSUE TITLE
Uncaught exceptions in Spicetify.CosmosAsync for non-JSON responses

### ISSUE THREAD

**Issue by JanitorialMess** [spicetify/cli#3164]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.45.454.gc16ec9f6
- Spicetify version: v2.38.3
```

### 📝 Description

I've noticed an issue with the error handling in `Spicetify.CosmosAsync.get`. It doesn't properly handle asynchronous promise rejections (synchronous try/catch blocks don't catch asynchronous promise rejections like those thrown by `res.clone().json()`). 

https://github.com/spicetify/cli/blob/ae905881c00ac6594651fa540197fd36f756f399/jsHelper/spicetifyWrapper.js#L416-L431

## Steps to Reproduce
* Use Spicetify.CosmosAsync to request a non-JSON resource (e.g., an image or audio file)
* Check console for uncaught promise rejections

```js
await Spicetify.CosmosAsync.get('https://download.samplelib.com/mp3/sample-3s.mp3')
```

## Proposed Solution
Refactor the error handling to use promise chaining instead of nested try/catch blocks.

**Comment by rxri** [comment]
Then don't use cosmosasync. Spotify's cosmos async didn't have error handling for this either.
