### ISSUE TITLE
Marketplace doesnt allow to install anything more extensions or anything

### ISSUE THREAD

**Issue by IVIPOWER** [spicetify/cli#3165]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: uh idk
- Spicetify version: same like spotify lol, the lastest ig but its been like this for a few updates

Windows 10
```

### 📝 Description

idk if is a theme thing (which i doubt bc it didnt happened earlier) or bc of an extension or something, please help? i could join discord or leave my discord to send pics if needed

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/1cb63752-2227-425f-aa80-4202f675aa4a)

**Comment by IVIPOWER** [comment]
btw, i did not cut anything, thats the marketplace (here full pic)
![image](https://github.com/user-attachments/assets/eccc57a9-7c95-4a0c-b6ee-1bab81906a87)

**Comment by rxri** [comment]
Don't know what latest is. You don't have latest marketplace installed (re-install it with command listed on the docs). Not related to cli.

**Comment by IVIPOWER** [comment]
what command?
