### ISSUE TITLE
Double marketplace icon issue

### ISSUE THREAD

**Issue by lovepilled** [spicetify/cli#3167]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.45.454.gc16ec9f6
- Spicetify version: v2.38.3
```

### 📝 Description

After messing around with themes in the marketplace, uninstall and installing new ones, my spicetify is stuck two marketplace icons. I have tried properly uninstalling and reinstalling spicetify but the problem persists even after.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/b1575067-6ba1-4308-8c48-b08d62920cf6)

**Comment by rxri** [comment]
![image](https://github.com/user-attachments/assets/942805f2-a3ba-446e-a463-2b18d7050ad4)
Fixed with https://github.com/spicetify/cli/commit/768cb4be44438205b482eef622fdf4f98e0b0232
