### ISSUE TITLE
Playlist empty

### ISSUE THREAD

**Issue by manavchaudhary1** [spicetify/cli#3171]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Flatpak com.spotify.Client 1.2.42.290.g242057a2
- Spicetify version: v2.38.3
```

### 📝 Description

Playlist empty on Spotify Client on Web it still listing all items in playlist.
OS-Fedora 40 

### 📸 Screenshots

![Screenshot from 2024-09-18 17-06-20](https://github.com/user-attachments/assets/71d6af65-f44c-4895-ba69-25f27b10ab3a)
![Screenshot from 2024-09-18 17-06-29](https://github.com/user-attachments/assets/e585778c-b31a-4470-9a2a-6357dee74e41)
![Screenshot from 2024-09-18 17-09-23](https://github.com/user-attachments/assets/feb09dff-f918-4847-a526-44924b4706d0)

**Comment by rxri** [comment]
Not related to spicetify
