### ISSUE TITLE
Want Musixmatch Api Intergrated Custom App In Spicetify 

### ISSUE THREAD

**Issue by Aseem-ibn-imthiyas** [spicetify/cli#3172]
### 📝 Provide a description of the new feature

Hi, Recently I Noticed Something Lag in Lyrics Plus 

can your dev team integrate Musixmatch directly as custom app in spicetify

its very helpful to get relief from stress

**Comment by rxri** [comment]
Then set global delay?

**Comment by Aseem-ibn-imthiyas** [comment]
i didn't got properly 

can u explain or any source
