### ISSUE TITLE
LyricsPlus CustomAPP | Karaoke word lyrics goes in reverse in Hebrew

### ISSUE THREAD

**Issue by PiterWeb** [spicetify/cli#3173]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bits) 1.2.45.454.gc16ec9f6
- Spicetify version: 2.38.3
```

### 📝 Description

Using the Lyrics Plus CustomAPP i have this bug:

In karaoke mode at least in Hebrew the order of the words is respected but not the order of the leters. The normal behavior would be that the word appear from right to left but right now do the oposite. 

### 📸 Screenshots

https://github.com/user-attachments/assets/df18ac8f-6b2e-4940-9b2a-6a2c84fef79a

**Comment by rxri** [comment]
Would require special css and detection of hebrew. Not feasible to implement.
