### ISSUE TITLE
Not working context menus on Spotify 1.2.47

### ISSUE THREAD

**Issue by f4taaal** [spicetify/cli#3177]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364.gf06e5cee
- Spicetify version: 2.38.3
- SO: Windows 11 23H3 64bit
```

### 📝 Description

Forced new navbar on recent update, clicking on the profile icon erases completely the UI.
EDIT: Actually any context menu (ex: right click on something) erases the item shelf and don't open nothing.

### 📸 Screenshots

![spotify](https://github.com/user-attachments/assets/76b44506-3bea-4589-8baf-6fead921b9bf)
![wtf is happening](https://github.com/user-attachments/assets/626d4265-7c75-4ce6-9292-28584b3b7b5c)

**Comment by sanoojes** [comment]
Spicetify currently doesn't support Spotify version 1.2.47. Please consider downgrading to a previous version in the meantime.

You can find Spotify installation files for various versions in this spreadsheet created by amd64fox: https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok

**Comment by daveningfr** [comment]
when will spicetify support this spotify version?

**Comment by rxri** [comment]
Fixed by https://github.com/spicetify/cli/commit/8e1926d2994c01e71dc32f666eef12675b0f2102
