### ISSUE TITLE
UI Broken After Latest Update

### ISSUE THREAD

**Issue by Veran04** [spicetify/cli#3178]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: 2.38.3
```

### 📝 Description

After the most recent spotify update causing my UI to break, I did the same steps I usually take which are:
1. Open command line
2. type "spicetify update"
Typically this is all I have to do and then my theme is reapplied. However in this case, the theme was applied in a very buggy way. You can see in the attached image that the panel on the right hand side (now playing view) takes up half the screen, and the bar you would typically drag to resize this does not work. I also get an error about needing to run the command spicetify sidebar_config 0 so I tried that and reapplied which made me stop receiving the error message but did not fix any of the UI issues. My extensions (shuffle+) are also not working currently.

### 📸 Screenshots

![{5EF53361-6C96-4B59-9FA5-6B15EA130466}](https://github.com/user-attachments/assets/2b819ce3-51b6-4183-bfcc-a3d25fb34d6e)

**Comment by rxri** [comment]
That's theme issue

**Comment by Veran04** [comment]
> That's theme issue

Where can I get help troubleshooting it then?

**Comment by Veran04** [comment]
I got help fixing a theme issue on the issues thread before, can you reopen this and let a developer check it out?

**Comment by machinemessiah** [comment]
> I got help fixing a theme issue on the issues thread before, can you reopen this and let a developer check it out?

Go to the marketplace, then go to themes (or installed), then click on the title text for the theme you have installed and it will link you to the actual git repo for that theme, THAT is where you need to report your issue, the theme developer is the one you need to talk to, this is not the right repo to report these issues.

Hope that helps!
