### ISSUE TITLE
UI Issue After latest update (may be a theme issue, please point me to the right spot and dont just close the issue with a comment that says "theme issue", that does not help at all)

### ISSUE THREAD

**Issue by Veran04** [spicetify/cli#3179]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: 2.38.3
```

### 📝 Description

After the most recent spotify update causing my UI to break, I did the same steps I usually take which are:

Open command line
type "spicetify update"
Typically this is all I have to do and then my theme is reapplied. However in this case, the theme was applied in a very buggy way. You can see in the attached image that the panel on the right hand side (now playing view) takes up half the screen, and the bar you would typically drag to resize this does not work. I also get an error about needing to run the command spicetify sidebar_config 0 so I tried that and reapplied which made me stop receiving the error message but did not fix any of the UI issues. My extensions (shuffle+) are also not working currently.

### 📸 Screenshots

![{90C1AFDF-DE00-42F8-ADAF-07E997A8D18B}](https://github.com/user-attachments/assets/34da4c61-f683-425b-8439-d7ae08f48d10)

**Comment by rxri** [comment]
Why did you create it again? It's theme issue. Disable the theme. I don't know what else I'm supposed to tell you. GitHub Issues are not for general help.

**Comment by Veran04** [comment]
tell me where to post it like the title says and stop being fucking lazy jesus lmao
