### ISSUE TITLE
Can't enable updates block

### ISSUE THREAD

**Issue by LolaMan** [spicetify/cli#3184]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.45.454.gc16ec9f6
- Spicetify version: v2.38.3
```

### 📝 Description

I am trying to stop spotify from updating using the command but it is giving me the same error in powershell no matter what I try

`PS C:\Windows\system32> spicetify spotify-updates block`

`fatal open C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.245.454.0_x64__zpdnekdrzrea0\Spotify.exe: Access is denied.`

I tried running powershell in admin and also using cmd but same result saying access is denied

**Comment by rxri** [comment]
Well, you won't be able to do it on Microsoft Store version. Windows limitation.
