### ISSUE TITLE
Duplicating marketplace icon and lyrics plus icon

### ISSUE THREAD

**Issue by Climax12** [spicetify/cli#3185]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.45.454.gc16ec9f6 (linux AUR)
- Spicetify version: 2.38.3 (linux AUR)
```

### 📝 Description

After latest spotify update marketplace and lyrics plus icons were duplicated on global nav bar but not on old side bar

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/4436e34d-9564-4ac8-add4-8446bc18c991)

**Comment by rxri** [comment]
Already fixed upstream by https://github.com/spicetify/cli/commit/768cb4be44438205b482eef622fdf4f98e0b0232
