### ISSUE TITLE
When opening volume spotify acts as if it is at 100% volume

### ISSUE THREAD

**Issue by AshKxK** [spicetify/cli#3186]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364.gf06e5cee
- Spicetify version:v2.38.4
```

### 📝 Description

Since a few days spotify plays at 100% volume until i change its volume( it shows its at 50%, for example, but plays at 100%.

**Comment by rxri** [comment]
Not spicetify related. The backend (app itself) doesn't seem to remember the volume or some extension does it.
