### ISSUE TITLE
Spicetify won't work on Linux

### ISSUE THREAD

**Issue by NyaomiDEV** [spicetify/cli#3187]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364
- Spicetify version: 2.38.4
```

### 📝 Description

Spotify won't start if Spicetify is applied to it.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/bf8a2a1f-0e4e-4009-9bcd-9fd0cf999bee)

**Comment by rxri** [comment]
Apparently a bug when using `yay` or something. We don't control it so idk how are we supposed to fix it.

**Comment by crimist** [comment]
Fixed in the AUR package at [c6b10a1](https://aur.archlinux.org/cgit/aur.git/commit/?h=spicetify-cli&id=c6b10a170b3c38115cf159966a8f851a53b07129)

**Comment by NyaomiDEV** [comment]
@crimist I know, I helped the maintainer :P
