### ISSUE TITLE
Marketplace error when applying

### ISSUE THREAD

**Issue by DestopLine** [spicetify/cli#3188]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364.gf06e5cee (aur/spotify 1:1.2.47.364-1 (+167 8.66))
- Spicetify version: 2.38.4 (aur/spicetify-cli 2.38.4-2 (+58 2.21))
- OS: Arch Linux x86_64
```

## Steps to reproduce
- Update packages `spotify`, `spicetify-cli` and `spicetify-marketplace-bin` to the latest version available in the Arch User Repository through an AUR helper
- Run `spicetify backup apply`
- One (or two) lines of the output say `error Custom app "marketplace" not found.`
- Spicetify marketplace on Spotify, and its extensions, don't work

I already tried reinstalling both Spicetify packages, but it did't work.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/eff17117-a7fb-498a-b87f-c06c16ac2858)
![image](https://github.com/user-attachments/assets/5e7c2342-ef8f-4341-9cf7-df24f9f452a8)

**Comment by rxri** [comment]
use marketplace install script to install it again then

**Comment by rxri** [comment]
spicetify-marketplace-bin won't work because `spicetify-cli` pkgbuild was changed

**Comment by DestopLine** [comment]
Reinstalling marketplace through install script worked, thank you.
