### ISSUE TITLE
Local files cause spotify to be much louder than it should be.

### ISSUE THREAD

**Issue by SkeJm** [spicetify/cli#3189]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364.gf06e5cee
- Spicetify version: v2.38.4
```

### 📝 Description

I'm having a problem with playing local files songs. 
Whenever it plays it turns my volume up (not the spotify volume bar, but spotify volume in general). And no it's not the local files being loud, because when I change the volume with spotify bar then it's back to normal.  Also when I fix the volume, when the song ends next one is also earraping me.
I'll provide proof if needed.

**Comment by rxri** [comment]
That's spotify bug. We do not change anything in the backend - the app (where local files are controlled).
