### ISSUE TITLE
Smart Shuffle ignored by spotify after activating it (since new update)

### ISSUE THREAD

**Issue by n0ia96** [spicetify/cli#3191]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Version:
Spotify para Windows (64 bits)
1.2.47.364.gf06e5cee
Spicetify v2.38.4

Country:
Portugal (Netherlands VPN bypass)
(I had to do this so xManager would work on mobile)
```

### 📝 Description

I've always liked smart shuffle because it showed me a lot of new songs for my playlists (for me, is one of the best features, even tho I've seen everywhere that people hate it ?????).

So, since I've updated my spicetify the feature stoped working.
Previously I had to:
- Go to "Experimental Features";
- Search for "Enable Smart Shuffle";
- Activate it, and then close spotify (the process itself)
- Open spotify again and go to "Experimental Features";
- Search again for "Enable Smart Shuffle" and deactivate it and turn it on again;
- Now when you click on the shuffle btn near unpause it add new songs to the queue;

So after this, it would previously work. Not anymore, how can I "fix" this?

Now what happens is that the songs show in queue, but disappear after 1s of you clicking in shuffle, and smart shuffle changes back to the normal shuffle.

### 📸 Screenshots

I just changed from shuffle to normal shuffle to smart shuffle, then it changed alone back to normal shuffle.
Notice how the smart shuffle songs disappear after appearing.

![gif of the spicitify issue](https://i.imgur.com/uJEvJgB.gif)

**Comment by rxri** [comment]
If you’re using adblockify, then it disables it forcefully because smart shuffle is broken.
