### ISSUE TITLE
Lyrics Plus bad animation

### ISSUE THREAD

**Issue by MBNpro-ir** [spicetify/cli#3193]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64-bit)
1.2.47.364.gf06e5cee
Spicetify v2.38.4
```

### 📝 Description

When a few lines of lyrics are passed, the animation of changing the lines is broken and seems to be lagging.
It works fine for the first few seconds or the first few lines, but after a few lines, it lags.

### 📸 Screenshots

![Screenshot_1](https://github.com/user-attachments/assets/325be50d-b245-47c7-bd88-b6dd694b5540)

**Comment by rxri** [comment]
Issue is not a lyrics plus

**Comment by MBNpro-ir** [comment]
What do you mean is not a issue?
