### ISSUE TITLE
Spotify keeps restarting and eventually quits

### ISSUE THREAD

**Issue by JustAFridg** [spicetify/cli#3195]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.47.364.gf06e5cee
Spicetify v2.38.4

I'm using Spicetify on my personal computer with a ryzen 7 5700x and a 7600xt combined 
with 32gb of ddr4-3600 ram. The operating system is Windows 11 64 bit version 23H2.
```

### 📝 Description

Every time I start up Spotify with spicetify installed, it shows a black screen and after some time it shows the home page for a second and then it completely reloads, repeating everything again. After about 3 cycles, it quits the app. I cannot figure out anything to fix it... I tried updating Spotify, Spicetify, enableling or disabeling themes and extensions, but nothing worked.

### 📸 Screenshots

https://github.com/user-attachments/assets/33b53a84-25d5-44e7-9bdf-e091744939b2

**Comment by rxri** [comment]
Not related to spicetify. Just reinstall spotify.
