### ISSUE TITLE
Sidebar Marketplace icon not showing

### ISSUE THREAD

**Issue by Gabriel-TheoChem** [spicetify/cli#3198]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify para Windows (64 bit)
1.2.48.405.gf2c48e6f
- Spicetify version: - Spotify version: Spotify for Windows (64 bit)
```

## Trying install Marketplace (to use AdBlock extension) ##
I tried to install the Spicetify Marketplace on Spotify client, but it's not working. I walked trought the installation guide available on [Getting Started](https://spicetify.app/docs/getting-started) (using a win powershell both 5 and 7) in administrator mode and the conventional one -- I recieved (in both cases) the "Done!" message at the end but no window showed up after that, and the Marketplace icon didn't show up as well.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/3a61c82f-4bd4-4f03-848a-70a96ee2a87a)

**Comment by rxri** [comment]
`spicetify backup apply`. If you require additional help, please ask for it via discord server

**Comment by Gabriel-TheoChem** [comment]
Thanks for the feedback. How to run `spicetify backup apply`? Wait for a update? I checked the [Spicetify Update](https://spicetify.app/docs/getting-started/#updating) for some help, but I couldn't find anything.

**Comment by aaroncarson-monzo** [comment]
@Gabriel-TheoChem in your terminal :)

**Comment by caraar12345** [comment]
@Gabriel-TheoChem in your terminal :)

**Comment by TheoAlchemist** [comment]
It worked! Thanks a lot!

**Comment by GreenEnthusiast** [comment]
I've tried every method and it still wont appear I can install themes just fine manually though

**Comment by arLevi** [comment]
It suddenly disappeared for me as well ...
