### ISSUE TITLE
keyboardShortcut.js: pressing `/` to search no longer works

### ISSUE THREAD

**Issue by rien333** [spicetify/cli#3200]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364.gf06e5cee
- Spicetify version: 2.38.4
- OS: Arch Linux
```

### 📝 Description

`Extensions/keyboardShortcut.js` provides <kbd>/</kbd> as a search key, as in vim. 

However, somewhat recently (probably during the 1.2.47 update, which  revamped the search bar), this shortcut key has stopped working.

More specifically, spotify goes into "searching mode", but the search bar itself remains unfocused.

**Comment by rxri** [comment]
`/` shortcut only redirects to `/search`. If it did focus search bar, then it was on spotify side and not ours.

https://github.com/spicetify/cli/blob/main/Extensions/keyboardShortcut.js#L55

**Comment by rien333** [comment]
> / shortcut only redirects to /search

This is a good technical explanation of _why_ this issue occurs, but misses the intent behind this bug report and/or the extension. 
The intended behavior of the <kbd>/</kbd> bind is — and always has been —  to match the functionality of the built-in <kbd>Ctrl-L</kbd> shortcut.  That it now simply redirects to `/search` is an implementation-level detail, without any special significance —  <kbd>/</kbd> [has not always been a simple redirector](https://github.com/spicetify/cli/blob/81843b10d569ea90bb8136b69720b81edb27f265/Extensions/keyboardShortcut.js#L167). This current  implementation worked for a while, but now it no longer does. 

Of course, closing this because of a lack of interest is perfectly valid, but at that point I feel like extensions should be maintained out of tree (which I feel  like is in the works?)
