### ISSUE TITLE
`restart` command doesn't start the Spotify client if it's not yet open

### ISSUE THREAD

**Issue by aureliony** [spicetify/cli#3202]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.46.462.gf57913e0
- Spicetify version: 2.38.4
- OS: Windows 10
```

### 📝 Description

Close the Spotify client and run the command `spicetify restart`.

Expected: The Spotify client is started.
Actual: The Spotify client is not started.

**Comment by rxri** [comment]
Like the command states, it restarts...

**Comment by aureliony** [comment]
That's a bummer. Intuitively "restart" means it should start if not already started.

**Comment by rxri** [comment]
> That's a bummer. Intuitively "restart" means it should start if not already started.

That command is just for restarting. It exists because there's already function used for restarting Spotify across the CLI
