### ISSUE TITLE
Doesn't save window position (or forcefully centers window)

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [spicetify/cli#3203]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364
- Spicetify version: 2.38.4
```

### 📝 Description

Dimensions are saved but the window is always centered horizontally and vertically instead of the last position.
Never had this problem before using spicetify.

**Comment by rxri** [comment]
Not spicetify's fault. We do not control the window behavior
