### ISSUE TITLE
Installation script incorrectly says PowerShell is not in admin

### ISSUE THREAD

**Issue by ydrk** [spicetify/cli#3205]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: N/A
- Spicetify version: N/A
```

### 📝 Description

Run Powershell as an admin and run the installation script

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/a918bd3e-5f08-4893-b2a9-69ff5ad0fdec)

**Comment by ydrk** [comment]
Nvm im an idiot

**Comment by rxri** [comment]
happens to best of us
