### ISSUE TITLE
Latest Spotify update compatibility tracker

### ISSUE THREAD

**Issue by wenbang24** [spicetify/cli#3206]
### 📝 Provide a description of the new feature

Whenever Spotify is updated and Spicetify doesn't work, I am always skeptical to whether my local installation of Spotify/Spicetify is broken, or Spicetify hasn't been updated to work with the latest version of Spotify.
A little indicator showing whether Spicetify works on the latest version of spotify on the docs page (maybe on navbar) would be nice; is this feasible?

**Comment by rxri** [comment]
v3 already implements it
