### ISSUE TITLE
Spicetify not working

### ISSUE THREAD

**Issue by Dimetro25** [spicetify/cli#3209]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: dont know 
- Spicetify version: 2.38.4
```

### 📝 Description

Spicetify just stopped working. Tried reinstalling both Spotify and Spicetify.

**Comment by rxri** [comment]
You say nothing that could help me identify your issue. Re-apply spicetify then. Need help? Discord server is for it.
