### ISSUE TITLE
cannot open custom apps

### ISSUE THREAD

**Issue by sjp2511** [spicetify/cli#3210]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: --unknown--
- Spicetify version: 2.38.4
```

### 📝 Description

cannot open any custom apps

**Comment by rxri** [comment]
You don't provide anything. No screenshot, no console log... Spicetify v2.38.4 works on 1.2.49 and others. Closing. If you need help, join our discord server
