### ISSUE TITLE
Gradient broken in Spicetify

### ISSUE THREAD

**Issue by Mysticc28** [spicetify/cli#3211]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.49.439.gfae.492c7
- Spicetify version: v2.38.4
```

### 📝 Description

The top of any playlist has the default background gradient and does not blend in with the 'Apple Music Gradient' even though the 'Remove top gradient' along with 'Smooth Reveal Playlist Gradient' snippets are enabled along with each other or by themselves alone. Similarly, 'No Controls ohitstom' extension does not work or appears blank as can be seen in screeenshot below where it has been enabled. Have reinstalled Spotify application, blockthespot.bat and Spicetify multiple times along with resetting marketplace and all settings but problem still persists. The fullscreen mode for 'Beautiful Lyrics' is also broken with out of place elements.

### 📸 Screenshots

![image_2024-10-25_005355725](https://github.com/user-attachments/assets/8e65e83d-9a40-40ec-99dd-6ae7960c8a68)
![image_2024-10-25_005857868](https://github.com/user-attachments/assets/5603593f-3868-462c-abb9-a68de5ca80fb)

**Comment by rxri** [comment]
That's theme issue though. Spicetify does not modify CSS by default.
