### ISSUE TITLE
Error: /snap/bin/spotify is not a valid path

### ISSUE THREAD

**Issue by sixcy** [spicetify/cli#3213]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.45.454.gc16ec9f6
- Spicetify version: 2.38.4
- OS : Ubuntu 22.04
```

### 📝 Description

When running "spicetify restart", I get : 
```
error /snap/bin/spotify is not a valid path. Please manually set "spotify_path" in config-xpui.ini to correct directory of Spotify.
```

I modified config-xpui.ini to set the path to spotify, on my system it is /snap/bin/spotify as I installed it with snap

What is the preferred way to install spotify for spicetify to work?

**Comment by rxri** [comment]
Per our docs, snap containers are immutable to changes. You can't modify anything inside them. Install Spotify via apt or different package manager.
