### ISSUE TITLE
[Lyrics-Plus] Lyrics-Plus karaoke error

### ISSUE THREAD

**Issue by Fortress937** [spicetify/cli#3214]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.49.439.gfae492c7 
- Spicetify version: v2.38.4
```

### 📝 Description

It work once before when playing this songs, but now every time i play the same songs and going into lyrics-plus karaoke section, it keep showing this error, look at the screenshot below.

I'm not sure if server fetching issues, conflict with other extensions, or outdated? (sorry my English might be bad)

### 📸 Screenshots

![Screenshot 2024-10-29 192324](https://github.com/user-attachments/assets/45f2dc73-cc8a-40e2-b4cc-b2800b205259)

**Comment by rxri** [comment]
Then disable the unnecessary providers. Not a bug.

**Comment by Fortress937** [comment]
you mean disable unnecessary extensions?

**Comment by Fortress937** [comment]
> Then disable the unnecessary providers. Not a bug.

That did not help, the same thing keep happening

**Comment by Fortress937** [comment]
because of this, i will uninstall lyrics-plus and head to the beautiful lyrics instead. So disappointing.

**Comment by rxri** [comment]
> Disabling any providers such as extensions or custom apps does not help!! Because of this, i will uninstall lyrics-plus and head to the beautiful lyrics instead. So disappointing.

and... refresh musixmatch token. All of the providers work just fine from my testing.

**Comment by Fortress937** [comment]
hmm...for that method of refreshing musixmatch token, how to do that? sounds like something related to dev tools?

**Comment by Fortress937** [comment]
nvm, it's in the lyrics plus config setting in the profile page.

**Comment by Fortress937** [comment]
Thanks for the effective and great solution, although appeared to be temporary fix, but the problem happens again after playing few music more.
![Screenshot 2024-11-08 103814](https://github.com/user-attachments/assets/e54c14eb-d16e-4ac9-857b-b8c32aaf430a)

**Comment by Fortress937** [comment]
it's likely that musixmatch token has been flagged for some reason, refreshing musixmatch token provide temporary fix, but the problem happen again after a while.

**Comment by rxri** [comment]
> it's likely that musixmatch token has been flagged for some reason, refreshing musixmatch token provide temporary fix, but the problem happen again after a while.

It's not being flagged, it's being rate limited. Happens. We can't make it work in any other way
