### ISSUE TITLE
Add help command

### ISSUE THREAD

**Issue by erikhuizinga** [spicetify/cli#3215]
### 📝 Provide a description of the new feature

I tried `spicetify help` for the command to fail with message: use `spicetify -h`. Well, that's probably what it should do right away, don't you think? ;)

**Comment by rxri** [comment]
Thats how CLI apps work

**Comment by erikhuizinga** [comment]
`git`, `docker`, `npm`, `brew` and many others would disagree. 😉 

I know it's not some standard or best-practice. But it is very common.

**Comment by erikhuizinga** [comment]
Furthermore, the `spicetify` cli does uses command keywords already (e.g. `spicetify path`).

Anyways, thanks for considering my feature request.

**Comment by rxri** [comment]
> `git`, `docker`, `npm`, `brew` and many others would disagree. 😉
> 
> I know it's not some standard or best-practice. But it is very common.

Per v2.38.0, spicetify v2 is in maintenance mode and does not consider adding new features. Again, this is not very common thing to implement, so it won't be considered.

**Comment by erikhuizinga** [comment]
Thanks for the notive! I'm not sure exactly what you mean by maintenance mode. Can you link to some issue, announcement, post, or just reply what that means? Is v3 coming, or the entire cli no longer being developed?
