### ISSUE TITLE
Low res icon (in startallback etc)

### ISSUE THREAD

**Issue by Anutim** [spicetify/cli#3217]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.49.439.gfae492c7
- Spicetify version: 2.38.4
- OS: Windows 24H2
```

### 📝 Description

Apps like Startallback try to dynamically update icons during a program running if it can find any (don't know exactly how though).

After installing Spicetify and restarting however, whenever Spotify is running the icon gets updated to a lower resolution/blurry version.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/547e76e9-5802-4dcf-bb3f-9e9f26544b55)

**Comment by rxri** [comment]
Spicetify does not modify the executable. Issue should be raised in their support form or forums.
