### ISSUE TITLE
Unusual fatal error on Mac terminal

### ISSUE THREAD

**Issue by 777sable** [spicetify/cli#3221]
To preface this, the Mac I'm using Spicetify on is administration-owned. However, even when using admin permissions and running `spicetify update`, `apply` and `backup apply`, I was given the following line:

`fatal unlinkat /Applications/Spotify.app/Contents/Resources/Apps/xpui.spa: permission denied`

I have checked the FAQ & older posts.

- Spotify version: Spotify for macOS (Apple Silicon)
1.2.50.335.g5e2860a8
- Spicetify version: spicetify v2.38.4

**Comment by rxri** [comment]
Then uh... apply permissions? If your account doesn't have admin perms its better you won't use spicetify

**Comment by rxri** [comment]
Well, it's on your end really so can't really help because I don't know what happened or what you did prior to that
