### ISSUE TITLE
Lyrics plus not working

### ISSUE THREAD

**Issue by Dimetro25** [spicetify/cli#3222]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.50.335.g5e2860a8
- Spicetify version: v2.38.4
```

### 📝 Description

The lyrics plus plugin/addon doesn't work at all it just show a blank icon and something went wrong. I tried reinstalling it.

### 📸 Screenshots

![image_2024-11-15_212155567](https://github.com/user-attachments/assets/8135e1f7-d6c4-47cc-a584-65a4e770d3c2)

**Comment by rxri** [comment]
`spicetify config custom_apps lyrics-plus`. Remove the other ones from the config which is available at `spicetify config-dir`.

**Comment by Dimetro25** [comment]
The thing is that in the custom_apps folder I have nothing. I don't know how to delete the other ones.

**Comment by sanoojes** [comment]
> The thing is that in the custom_apps folder I have nothing. I don't know how to delete the other ones.

remove the custom apps from `config.xpui.ini`

**Comment by Dimetro25** [comment]
Thx I did that but when I install lyrics plus again I get an error and the icon appears as blank again
![image_2024-11-16_201859568](https://github.com/user-attachments/assets/d8dc0896-bced-47fd-9e8a-c2e75ccd3847)

**Comment by sanoojes** [comment]
maybe a reinstall will fix the issue

**Comment by Dimetro25** [comment]
Ok thx
