### ISSUE TITLE
Changing keybinds in keyboardShortcut.js doesn't work

### ISSUE THREAD

**Issue by h3nr1-art** [spicetify/cli#3223]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.2.50.335-1
- Spicetify version: 2.38.4
```

### 📝 Description

Hello, i'm trying to configure my keybinds, so i tried deleting a shortcut : The shortcut still works, i tried changing the shortcut still not working.

I tried that with every variable, it simply doesn't work.

**Comment by rxri** [comment]
Re-apply spicetify afterwards
