### ISSUE TITLE
Disable DevTools

### ISSUE THREAD

**Issue by Fortress937** [spicetify/cli#3225]
### 📝 Provide a description of the new feature

Few reasons why i asked to request a features of disabling devtools:
1. I don't like devtools to be enabled all the time.
2. I don't feel safe of having devtools enabled on spotify. Additionally, some malicious code can run.
3. Most of the time, devtools isn't necessary for me, only i use devtools in extreme cases, such as reporting bugs.
4. Very Rarely, devtools can breaks stuffs in spotify if misused.
5. My friends sometimes misused my spotify's devtools, i want this to stop!

### ➕ Additional Information

Features to implement:
1. Disable devtools through powershell.

(Requesting features aren't easy, getting features to be implemented depend on their popularity and developer's choices.)
(Unless there is a way to disable devtools, then this issues can be closed.)

**Comment by rxri** [comment]
It will disable itself when product state is refreshed

**Comment by rxri** [comment]
It will disable itself when product state is refreshed

**Comment by Fortress937** [comment]
> It will disable itself when product state is refreshed

hmm...how?

**Comment by Fortress937** [comment]
did you mean reload the spotify? (If yes, i actually did and the devtools still can be opened, i want to completely disable devtools)

**Comment by Fortress937** [comment]
nvm, it disabled once i update the spicetify, but that will be inconvenient since i have to wait for the next release to disable devtools.

**Comment by rxri** [comment]
> nvm, it disabled once i update the spicetify, but that will be inconvenient since i have to wait for the next release to disable devtools.

Product state refresh can happen any time. I don't know when. For 99.99% of people it's 1 or 2 hours

**Comment by Fortress937** [comment]
> > nvm, it disabled once i update the spicetify, but that will be inconvenient since i have to wait for the next release to disable devtools.
> 
> Product state refresh can happen any time. I don't know when. For 99.99% of people it's 1 or 2 hours

thanks for letting me to know this, too sorry i was asking too much question because i was curious about it, and between 1 or 2 hours seems to be an reasonable range.
