### ISSUE TITLE
HMR in Spicetify watch mode

### ISSUE THREAD

**Issue by Afterlifepro** [spicetify/cli#3228]
### 📝 Provide a description of the new feature

Spicetify has an incredibly useful feature for developing extensions where spotify automatically reloads when an extension updates (`spicetify watch`) however this forces the entire app to reload. If possible, it would be incredibly useful if HMR was added (like in vite and webpack) in order to save time and allow you to see tweaks to css instantly. Obviously this is not a dealbreaker and I'm unsure as to the possibility as to this in the first place (I assume it would be hard) however, if possible and practical, this would be a great feature!

### ➕ Additional Information

- [Vite](https://vite.dev/guide/features.html#hot-module-replacement)
- [Webpack](https://webpack.js.org/guides/hot-module-replacement/)
- [Parcel](https://en.parceljs.org/hmr.html)

**Comment by rxri** [comment]
It would require rebuilding how extensions work in the first place. It's not really feasible in v2. It's added in v3
