### ISSUE TITLE
Lyrics Plus doesn't appear when I installed it

### ISSUE THREAD

**Issue by sbief** [spicetify/cli#3233]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.52.442.g01893f92
- Spicetify version:2.38.5
```

### 📝 Description

Lyrics Plus doesn't appear and when I install it using Powershell (not admin) it says this:
warning Config ‘custom_apps’ unchanged: lyrics-plus is already in the list.
In the image, only Marketplace appears and Lyrics Plus should appear next to it.
Until 2 days ago it was working without any problem, I don't know what could have happened to make it not appear and tell me in Powershell that.
How can I solve it?

### 📸 Screenshots

![Captura de pantalla 2024-12-04 231352](https://github.com/user-attachments/assets/7b32554d-ecc6-420b-9374-a49169d1a8fd)
![Captura de pantalla 2024-12-04 231357](https://github.com/user-attachments/assets/402ff885-b5e2-42c3-8474-888fdcad7570)

**Comment by rxri** [comment]
![image](https://github.com/user-attachments/assets/adc6307a-e952-4e4a-84b5-b6e3239ef387)
do what it says.
