### ISSUE TITLE
Extensions Don't work

### ISSUE THREAD

**Issue by Landon15678** [spicetify/cli#3234]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.551.345.gcc39d911
- Spicetify version: v2.38.5
```

### 📝 Description

After updating Spicetify to the Latest Version all my Extensions Don't work like "adblockify" or the "Volume percentage" this is really annoying can you please fix it

**Comment by rxri** [comment]
Spicetify v2.38.5 works just fine with Spotify v1.2.51. Please reinstall spotify and re-apply spicetify.
