### ISSUE TITLE
Sidebar Config not available

### ISSUE THREAD

**Issue by noidesserts** [spicetify/cli#3238]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.52.442.g01893f92
- Spicetify version: Spicetify v2.38.5
```

### 📝 Description

Sidebar Config option disappeared, not available. Home config is there, but not sidebar config. I am using LibX Reborn, but the issue was there before.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/116a8b52-04c1-45fe-918e-e9b500ca8d83)

**Comment by noidesserts** [comment]
![image](https://github.com/user-attachments/assets/a3610f88-e85f-4a58-b94a-af3c168516cd)

**Comment by rxri** [comment]
Well it won't work with extensions that are "restoring" old ui of course. Not a bug.

**Comment by noidesserts** [comment]
It wasnt there before as well

**Comment by noidesserts** [comment]
not really relevant anyway
