### ISSUE TITLE
marketplace extensions gone?

### ISSUE THREAD

**Issue by bioshocked** [spicetify/cli#3239]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.52.442.g01893f92
- Spicetify version:2.38.5
```

### 📝 Description

About two weeks ago after spotify's new ui update i opened up spotify one day and my spicetify extensions on marketplace were gone. i'm not sure if it was something i did, i only used commands to update spicetify and its extensions like normal but none of these extensions have been showing up from what i see. i waited to post this since i thought it would be something that would get fixed later on but the marketplace 'installed' section is completely blank. i wouldnt mind reinstalling them but i had the bookmarks extension with a bunch of albums saved and wouldn't want to lose them all. im worried if i try reinstalling them on the marketplace my bookmarks will be completely lost. also, the couple extensions i downloaded manually in my extensions folder are still working fine. 
any advice on how to recover my extensions or would just reinstalling them give me back all the bookmarks i had?

**Comment by rxri** [comment]
Since you cleared spotify data, the installed extensions etc from marketplace are gone too.
