### ISSUE TITLE
[Lyrics Plus] Karaoke lyrics error even after disabling other provider and refreshing musixmatch token.

### ISSUE THREAD

**Issue by Fortress937** [spicetify/cli#3240]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.52.442.g01893f92  
- Spicetify version: v2.38.5
```

### 📝 Description

I was facing an issues retrieving an lyrics for lyrics plus. Things that i have tried:

- Refreshed musixmatch token
- Disabled all provider (including musixmatch itself) and re-enabled all of them again
- Moved musixmatch to the top
- Cleared spotify cache
- Reinstalled Lyrics plus

I've done all of these methods, but unfortunately, it didn't work.

### 📸 Screenshots

![Screenshot 2024-12-19 093004](https://github.com/user-attachments/assets/f699a387-3f94-4ac9-9e7a-d708f233373d)
The karaoke lyrics were working previously with this music, but now it no longer works (Now it happens to all music/songs).

![Screenshot 2024-12-19 093041](https://github.com/user-attachments/assets/86ac5d13-190e-4a9a-8632-459f3e02f365)
I do refresh the musixmatch token, disabled all provider (including musixmatch provider itself) and re-enabled it, and moving musixmatch to the top, but it did not work.

**Comment by rxri** [comment]
Then there's no karaoke mode (word sync) on the song on musixmatch. Don't know how much more we can help.

**Comment by rxri** [comment]
the proxy is working just fine so ummm... unless you show me network tab (`spicetify enable-devtools`, right click anywhere, click Inspect`) and show me the requests for musixmatch on discord then i could investigate i guess

**Comment by Fortress937** [comment]
> the proxy is working just fine so ummm... unless you show me network tab (`spicetify enable-devtools`, right click anywhere, click `Inspect`) and show me the requests for musixmatch on discord then i could investigate i guess

![Screenshot 2024-12-19 105124](https://github.com/user-attachments/assets/7cf6ce25-f3a1-4b99-811f-56889d0877b7)
sure

**Comment by Fortress937** [comment]
> Then there's no karaoke mode (word sync) on the song on musixmatch. Don't know how much more we can help.

Are you sure? Ok let's examine this.

![Screenshot 2024-12-19 105432](https://github.com/user-attachments/assets/48e1dc22-713e-4e7b-8aa0-bc5ac47effbb)
Previously, it work with this songs (Screenshot took at yesterday)

![Screenshot 2024-12-19 105207](https://github.com/user-attachments/assets/af7bbab2-43a0-494f-81bf-d7255f5dbe7d)
But now.....(This happened at today, today took a screenshot)

**Comment by Fortress937** [comment]
> > the proxy is working just fine so ummm... unless you show me network tab (`spicetify enable-devtools`, right click anywhere, click `Inspect`) and show me the requests for musixmatch on discord then i could investigate i guess
> 
> ![Screenshot 2024-12-19 105124](https://private-user-images.githubusercontent.com/119410273/397198271-7cf6ce25-f3a1-4b99-811f-56889d0877b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NzgwNzgsIm5iZiI6MTczNDU3Nzc3OCwicGF0aCI6Ii8xMTk0MTAyNzMvMzk3MTk4MjcxLTdjZjZjZTI1LWYzYTEtNGI5OS04MTFmLTU2ODg5ZDA4NzdiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwMzA5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWRkYzM1YTdhM2Q4NzJmNjc4YmYyMjlkNWRkZDdkNmQ5YTdiMzQ0OWM2MjJhM2JlNjM2NDRjMzg5OGM1YTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DPVSgJ602sNgu6vgxHHUz9UFcVPsUWhih1rzdsNwlsE) sure

(Edit: i do not have discord so i sent the network result here)

**Comment by Fortress937** [comment]
![Screenshot 2024-12-19 171315](https://github.com/user-attachments/assets/76cd7769-25cc-4f0d-8893-0d7a8a879650)
Ok for some reason, an error popup that resembles lyrics plus.

**Comment by Fortress937** [comment]
Now i get what's happening to the lyrics plus, because of musixmatch server ip rate-limiting.

**Comment by Fortress937** [comment]
Well, that did not fix my problem, adding cors url in spicetify cors template still lead to same results, kinda disappointing.
