### ISSUE TITLE
"Something went wrong, try reloading the page"

### ISSUE THREAD

**Issue by Potatovibin** [spicetify/cli#3241]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Can't check via the 3 dots
- Spicetify version: v2.38.5
```

### 📝 Description

Spotify just won't load, I've tried to completely reinstall Spotify, and Spotify works but spicetify doesn't

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/6263815e-4d33-4ff9-bdf2-24523b60bac0)

**Comment by rxri** [comment]
Reinstall spotify

**Comment by Potatovibin** [comment]
reinstalled it twice already still dosen't work

**Comment by Salman7236** [comment]
> Reinstall spotify

I reinstalled spotify and spicetify and it was working fine until I installed the volume percentage extenstion and now it's showing the same error again.

**Comment by patyhank** [comment]
> Reinstall spotify

Same error and resintalled with latest Spotify version (seems 1.2.53 with spicetify 2.38.6)
![image](https://github.com/user-attachments/assets/9949603e-18ba-4062-8cd4-00acb0d742d4)

**Comment by Potatovibin** [comment]
Sometimes it works sometimes it doesn't? Yesterday morning it didn't work but the same day night it did
