### ISSUE TITLE
i cant install Spicetify Marketplace

### ISSUE THREAD

**Issue by TheYali1** [spicetify/cli#3245]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.53.438.g246d60c9
```

### 📝 Description

iex : Program 'spicetify.exe' failed to run: Access is deniedAt line:16 char:1
+ spicetify path userdata | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:96
+ ... sercontent.com/spicetify/marketplace/main/resources/install.ps1 | iex
+                                                                       ~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Invoke-Expression], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed,Microsoft.PowerShell.Commands.InvokeExpressionCommand

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/a759ba50-6e63-4aa8-b2f4-81a85169073f)

**Comment by rxri** [comment]
Defender or your antivirus blocked spicetify executable
