### ISSUE TITLE
Return Genius Lyrics

### ISSUE THREAD

**Issue by MineyHax** [spicetify/cli#3247]
### 📝 Provide a description of the new feature

As in the old versions, Genius lyrics were present. These were useful for annotations of lyrics and listening to obscure/unreleased to streaming platforms music.

### ➕ Additional Information

As old version.

**Comment by rxri** [comment]
Won't happen. You can modify the lyrics-plus file to remove the block for newer versions and use YOUR OWN cors proxy.
