### ISSUE TITLE
Skipping stops music

### ISSUE THREAD

**Issue by vvirtues** [spicetify/cli#3248]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.53.438.g246d60c9

- Spicetify version: Spicetify v2.38.7
```

### 📝 Description

Skipping stops playback and causes the bottom bar to appear empty. only fix is to go to a different playlist and play a song from there. (same thing happens if you skip again)

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/e21f9af1-c2aa-4d03-b627-65ef8a937c46)

**Comment by rxri** [comment]
That's spotify bug on 1.2.53. Wait for an update from their end.

**Comment by IvanPinesLol** [comment]
thank god it's a bug, I thought it was spotify that pulled off something stupid like they did with the xmanager

**Comment by renntbenrennt** [comment]
Not sure about you guys, but it's this issue that was reported on Spotify community the same as mine. 

So it's caused by adding music to the queue, and to make the app back to normal is to clear the queue. (this works for me)

https://community.spotify.com/t5/Ongoing-Issues/Playback-issues-related-to-the-next-song-in-the-queue/idc-p/6609352

**Comment by Dhia-101** [comment]
Having the same issue here

**Comment by IvanPinesLol** [comment]
> Not sure about you guys, but it's this issue that was reported on Spotify community the same as mine.
> 
> So it's caused by adding music to the queue, and to make the app back to normal is to clear the queue. (this works for me)
> 
> https://community.spotify.com/t5/Ongoing-Issues/Playback-issues-related-to-the-next-song-in-the-queue/idc-p/6609352

It actually worked, thank you so much bro
