### ISSUE TITLE
song not playing when in queue

### ISSUE THREAD

**Issue by eggboi10** [spicetify/cli#3249]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.58.438.g246d60c9
- Spicetify version:2.38.7
```

### 📝 Description

basically, whenever i put a song in a queue, after the previous song ends, nothing plays when the queued song plays

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/34cd92f4-8ee4-4cd6-a992-004fef47be07)
![image](https://github.com/user-attachments/assets/f904c221-6f4d-49d0-96b2-18d6d6338fb2)
(man that face in the 2nd screenshot is accurate to what im feeling right now)

**Comment by rxri** [comment]
Spotify bug in 1.2.53. Wait for a update/fix from them. Not spicetify related.

**Comment by rxri** [comment]
Also 1.2.58 doesn’t exist xd

**Comment by eggboi10** [comment]
ah, my bad :P
