### ISSUE TITLE
lyrics plus scaling broken after update

### ISSUE THREAD

**Issue by VVispy** [spicetify/cli#3250]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.53.438.g246d60c9 (latest as of making)
- Spicetify version: 2.38.7 (latest as of making)
```

### 📝 Description

lyrics plus app scaling got broken (shorter at the bottom) after i updated from 1.2.46. this can be seen in the image where theres a black gap under it.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/5732ea22-6fbd-4d3a-b44d-c099666f8582)

**Comment by rxri** [comment]
This space is for ad banner from Spotify
