### ISSUE TITLE
[Shuffle+] When shuffle+ an album it repeats songs

### ISSUE THREAD

**Issue by megatron008** [spicetify/cli#3251]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.49.439.gfae492c7
- Spicetify version: v2.38.7
```

### 📝 Description

Hello, the issue happens when you try and shuffle+ the album option, it repeats songs, If i select with SHIFT control every song from the album lets say 15 songs they shuffle correctly. I posted pictures to better show the issue below. Thanks. 

### 📸 Screenshots

![Screenshot_1](https://github.com/user-attachments/assets/3da2a095-a09a-4619-8a8b-e4bd01f34059)
![Screenshot_2](https://github.com/user-attachments/assets/b7afc29e-947c-4438-a46c-78a7dfe9446d)
![Screenshot_3](https://github.com/user-attachments/assets/a4b75c8a-4f79-4e0f-b3e3-daa5be764981)

**Comment by rxri** [comment]
works just fine on my end.

**Comment by rxri** [comment]
oh also, shuffle+, yes, songs can repeat, that's the point of true shuffle ;)

**Comment by jo2dan94** [comment]
hi @rxri sorry to tag you. if i right click my playlist and do shuffle+ will it do true shuffle or do i have to do like he said and highlight all my songs then do shuffle+?

**Comment by rxri** [comment]
You can just click the playlist and it will shuffle everything inside of it. You can select multiple playlists and it will shuffle all of them as well.

**Comment by jo2dan94** [comment]
like true shuffle?

Sent from [Proton Mail](https://proton.me/mail/home) for Android.

-------- Original Message --------

**Comment by rxri** [comment]
It uses https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
