### ISSUE TITLE
Use `flatpak info -l` to auto-discover Flatpak installation path

### ISSUE THREAD

**Issue by cyrneko** [spicetify/cli#3252]
### 📝 Provide a description of the new feature

Spicetify currently requires manual setup to be used with Flatpak, primarily due to the app being installed in different places depending on whether it's per-user or system-wide.

The Spicetify CLI should use the `flatpak info -l` command to discover the current Spotify installation directory. Data is returned simply as a string pointing to the current commit like this:
```
~ ❯ flatpak info -l com.spotify.Client
/var/lib/flatpak/app/com.spotify.Client/x86_64/stable/8c89d7ad6a8fa91bacda2f9f5a5d488f70d0d6acbd3773ba3f48f6e53b90a89f
```

It can then omit the last path (the commit) and replace it by `active`, adding the rest of the expected path (`files/extra/share/spotify/`) and use it as the `spotify_path`

### ➕ Additional Information

N/A

**Comment by rxri** [comment]
We don’t want to execute commands unless necessary (for example in the case of Windows Microsoft Store version). I’m pretty sure we have all paths where flatpak version can be.
