### ISSUE TITLE
[Lyrics-Plus] Add PetitLyrics as a lyrics provider in lyrics-plus

### ISSUE THREAD

**Issue by Fortress937** [spicetify/cli#3253]
### 📝 Provide a description of the new feature

I feel that lyrics-plus is a great custom apps to fetch lyrics from different sources (Musixmatch, Netease etc...), well maybe it will be good idea to add more lyrics provider? (Or probably bad). I've found that PetitLyrics can be a great one to be added to lyrics-plus as a provider.

**About PetitLyrics**
Petitlyrics is a service where many users can post synchronized lyrics that can be either (Plain Text = Unsynced), (Line Sync = Synced), or (Word Sync = Karaoke), most of them usually post word synced lyrics, which is karaoke lyrics, i heard that it can be used as a provider that fetch lyrics from them. [Petitlyrics](https://petitlyrics.com/en/)

**Something about API**
some people also requested to add petitlyrics as a [provider](https://github.com/whoeevee/EeveeSpotify/pull/247), but is in [different repository](https://github.com/whoeevee/EeveeSpotify)

It's nice to be added, but your choices.

### ➕ Additional Information

- Applied to Lyrics-Plus

**Comment by rxri** [comment]
Aren’t these taken from netease really. Not needed I think

**Comment by Fortress937** [comment]
> Aren’t these taken from netease really. Not needed I think

I don't think it was taken from netease, maybe they look familiar, if i'm not wrong, maybe try check it a bit since Netease and PetitLyrics wasn't a same thing, and i guess PetitLyrics was Japanese lyrics provider while Netease was Chinese lyrics provider??

**Comment by Fortress937** [comment]
Unless netease and petitlyrics work the same way, then i'm wrong, if you're aren't sure, explore it yourself.

**Comment by Fortress937** [comment]
Plus, Netease are open-source, while Petitlyrics are closed-source, there are a repository for [Netease](https://github.com/mantou132/Spotify-Lyrics), but for Petitlyrics, there isn't a way to check the source code from them (Unless you find it from EeveeSpotify repository, as they managed to get Petitlyrics API.)

**Comment by Fortress937** [comment]
whatever it's your choice, you don't need to add it, it just a suggestion that i willing to improve lyrics-plus, sounds wrong? i will never force you to do it, i just giving a small advice only and i'm kind enough to not force people to do such shit unnecessary stuff that will giving you a stress.

**Comment by Fortress937** [comment]
One thing to note that **Netease and Petitlyrics are both completely different**, they work independently, unless you want to replace netease with petitlyrics? Since netease are only for translation **(netease used to be able to provide the same functionality like providing unsynced, synced, and karaoke lyrics like Musixmatch and Lrclib, but now it just randomly display chinese lyrics that are incorrect and out of sync)** and petitlyrics will provide another available lyrics (typically same functionality with Musixmatch and Lrclib) or add it? (You don't actually need to do this anyway it's just your own choices, but replacing it **might be a good idea**.)

And idk what happened to netease nowdays, it will keep displaying incorrect chinese lyrics (it often happen to the instrumental musics as well). Anyway i fixed the problem with CORS, thanks for your help, and sorry for being harsh to you.
