### ISSUE TITLE
can't see playlists on sidebar after latest update

### ISSUE THREAD

**Issue by CzecDoggo** [spicetify/cli#3254]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.52.442
- Spicetify version: 2.38.7
```

### 📝 Description

I opened spicetify and all the saved and pinned playlists i had on the sidebar just disappeared.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/e395f6a7-57ce-4a9c-b11d-adf3bca680cc)

**Comment by CzecDoggo** [comment]
nvm sorry im just stupid my fault.

**Comment by DarkBlu242** [comment]
i made the same mistake it set to "downloaded" filter after update
