### ISSUE TITLE
Massive performance loss

### ISSUE THREAD

**Issue by om3ga6400** [spicetify/cli#3255]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: newest
- Spicetify version: newest
```

### 📝 Description

without spice: .5% cpu
with spice: 3-7 % cpu

**Comment by rxri** [comment]
Then don't use beautiful lyrics. Spicetify itself doesn't make a change

**Comment by om3ga6400** [comment]
> Then don't use beautiful lyrics. Spicetify itself doesn't make a change

i have no mods installed

**Comment by om3ga6400** [comment]
or anything else

**Comment by om3ga6400** [comment]
![{2D39A962-A133-4E39-B7C8-D6FC4D8EC7E8}](https://github.com/user-attachments/assets/3b16d681-1cbb-4079-9007-c51f09b092da)
default

![image](https://github.com/user-attachments/assets/3432c50c-d81a-4e6b-9c2a-751dfef5301e)
with spice

**Comment by rxri** [comment]
Okay so, cpu usage != performance loss. I don't know from where did you get that thing really... Spotify is using the same amount of cpu usage with both spicetify (+ custom apps etc) and without. You're getting the data from the time when spotify is minimized (efficiency mode on the first ss) and when it isn't.

**Comment by om3ga6400** [comment]
oops sorry, default 
![{7E8E1A80-04D3-4B33-AAC7-D186F905C1A4}](https://github.com/user-attachments/assets/3bc5cffd-4987-457f-82cb-ccb63a8db826)

**Comment by rxri** [comment]
Again, you're getting that data from one point of time. This tells nothing. Believe me or not, spicetify does not do anything that would make spotify use more CPU usage. I won't re-open issue because there's no issue. Again, you took this screenshot from the time where spotify is not doing anything.
