### ISSUE TITLE
Player Progress Incorrect

### ISSUE THREAD

**Issue by silora** [spicetify/cli#3256]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify Windows 1.2.53.438.g246d60c9
- Spicetify version: Spicetify v2.38.7
```

### 📝 Description

The progress information seems to be out of sync by ~1s when *the last song finishes and the next song continues to play*. But when *manually* skipping to the next song, this does not happen. Also, if the player is paused then start playing again it will be corrected. Here is an extension script I used to reproduce this bug:
```javascript
(function test() {
	console.log("Testing");
	lastPaused = 0;
	Spicetify.Player.addEventListener("songchange", ({ data }) => {
		console.log("=======Song changed========");
		wrong_beginning = Spicetify.Player.data.timestamp - Spicetify.Player.data.positionAsOfTimestamp;
		console.log("Timestamp of the song's beginning", wrong_beginning);
		setTimeout(async () => { 
			console.log("Restarting player by pause and play");
			Spicetify.Player.pause();
			Spicetify.Player.play();
			await new Promise(resolve => setTimeout(resolve, 500));
			correct_beginning = Spicetify.Player.data.timestamp - Spicetify.Player.data.positionAsOfTimestamp;
			console.log("Timestamp of the song's beginning now (fixed)", correct_beginning);
			console.log("Difference", correct_beginning - wrong_beginning);
			console.log("  ");
		}, 1000);
	});

	Spicetify.Player.addEventListener("onplaypause", ({ data }) => {
		if (Spicetify.Player.data.isPaused) {
			lastPaused = Date.now();
		} else {
			if (lastPaused > 0){
				console.log("<Paused for", Date.now() - lastPaused, ">");
				lastPaused = 0;
			}
		}
	});
})();
```

It also seems that the "songchange" event callback is called earlier than when the song actually started.

I don't know much js so I'm not sure if this is an actual bug, and if not I would love to know how to get the desired result!

### 📸 Screenshots

Here's the console output when *the last song finishes and the next song continues to play*: 
![image](https://github.com/user-attachments/assets/f5724b79-bf6a-43c5-8b85-822a03b21346)

Here's the console output when *manually* skipping to the next song: 
![image](https://github.com/user-attachments/assets/3deb50b9-6227-449d-99b8-a379a52ad826)

**Comment by rxri** [comment]
It can be out of sync so if you want the most up to date info use PlayerAPI and calculate timestamps

**Comment by rxri** [comment]
At the end of the day we relay on Spotify’s events so if they’re too slow then so will ours.

**Comment by silora** [comment]
I understand, thx for the comments!
