### ISSUE TITLE
lyrics plus in a separate window

### ISSUE THREAD

**Issue by Fatashinn** [spicetify/cli#3257]
### 📝 Provide a description of the new feature

<img width="1470" alt="Screenshot 2024-12-30 at 01 01 06" src="https://github.com/user-attachments/assets/97864bcb-d11b-46ae-bf66-994b9dbf5c09" />

### ➕ Additional Information

something like this? I think this would be a great feature, at lest it would be helpful for me.

**Comment by rxri** [comment]
popupLyrics exist. Lyrics Plus is a custom app, so no we cannot just put it into PiP.
