### ISSUE TITLE
themes are not persisting

### ISSUE THREAD

**Issue by Onur-Cansever** [spicetify/cli#3258]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.52
- Spicetify version: 2.38.7
```

### 📝 Description

When I applied new theme from marketplaces' themes section after I reboot computer  I see that the themes are gone.

**Comment by rxri** [comment]
Don’t use Microsoft store version of Spotify

**Comment by Onur-Cansever** [comment]
I have this issue with Gentoo Linux, hyrpland desktop. I have just installed spicefity from its sh script.

**Comment by rxri** [comment]
> edit: or don't clean the spotify data 🤷‍♀️ marketplace data is inside localstorage which is held inside spotify data...
