### ISSUE TITLE
[Lyrics Plus] Wrong Lyrics Shown

### ISSUE THREAD

**Issue by Blueartic37** [spicetify/cli#3260]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.53.438.g246d60c9
- Spicetify version: 2.38.7
```

### 📝 Description

**Steps to reproduce:**
1. Play "**Luv (sic) Grand Finale**"
2. Open Lyrics Plus karaoke tab
3. Make sure the lyrics is provided by "**Musicxmatch ● Writer(s):___**"

**What should have happened**
Lyrics Plus shows the lyrics to "**Luv (sic) Grand Finale**"

**What actually happens**
Lyrics Plus shows the lyrics to "**Luv (sic) pt4**"

### 📸 Screenshots

![Screenshot (147)](https://github.com/user-attachments/assets/219de4dc-9a01-45a9-be40-3e71274c9fe1)

**Comment by rxri** [comment]
Blame provider for giving wrong lyrics
